force-app/main/default/objects/FlexPoints_Transactions__c/FlexPoints_Transactions__c.object-meta.xml
<CustomObject>
    <label>FlexPoints Transactions</label>
    <nameField>
        <displayFormat>FPT-{0000}</displayFormat>
        <label>FlexPoints Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FlexPoints Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Lookup field so the permissions can be controlled independently from the account record. If roll ups are required then we can use managed package or apex class</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>FlexPoints Transactions</relationshipLabel>
    <relationshipName>FlexPoints_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/FlexPoint_Redemption_Case__c.field-meta.xml
<CustomField>
    <fullName>FlexPoint_Redemption_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The case that is associated with this particular redemption request.</description>
    <label>FlexPoint Redemption Case</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>FlexPoints Redemption</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>FlexPoints Transactions</relationshipLabel>
    <relationshipName>FlexPoints_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <description>The number of points being added or subtracted from a customer&apos;s points balance. Value can be positive (+) or negative (-)</description>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Requested Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <description>This field specifies the flexpoint transaction status</description>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Top Up</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Cancellation Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates the type of points this record is associated with.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Premier</fullName>
            </value>
            <value>
                <fullName>Advocacy</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Redemption</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/Service_Catalogues__c.object-meta.xml
<CustomObject>
    <label>Services Catalogue</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Service Catalogue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services Catalogue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Catalogues__c/fields/Account_Journey_Stage__c.field-meta.xml
<CustomField>
    <fullName>Account_Journey_Stage__c</fullName>
    <label>Account Journey Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New to Product</fullName>
            </value>
            <value>
                <fullName>In first year of using product</fullName>
            </value>
            <value>
                <fullName>Been using the product for some time</fullName>
            </value>
            <value>
                <fullName>Applicable to all</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Days_to_Deliver__c.field-meta.xml
<CustomField>
    <fullName>Days_to_Deliver__c</fullName>
    <label>Days to Deliver</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Delivered_By__c.field-meta.xml
<CustomField>
    <fullName>Delivered_By__c</fullName>
    <label>Delivered By</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Customer Success Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <label>Delivery Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bite Size</fullName>
            </value>
            <value>
                <fullName>Virtual Classroom</fullName>
            </value>
            <value>
                <fullName>Classroom</fullName>
            </value>
            <value>
                <fullName>1:1 Consulting</fullName>
            </value>
            <value>
                <fullName>1:Many Consulting</fullName>
            </value>
            <value>
                <fullName>Remote Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>Field to identify which division the service catalogue item is associated with</description>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Division</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Estimate_Required__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Leave the Points Conversion field empty and check this box if this Service requires our team to estimate the effort per customer request.</inlineHelpText>
    <label>Estimate Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Hours_to_Deliver__c.field-meta.xml
<CustomField>
    <fullName>Hours_to_Deliver__c</fullName>
    <label>Hours to Deliver</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Remote</fullName>
            </value>
            <value>
                <fullName>Onsite</fullName>
            </value>
            <value>
                <fullName>Access Office Location</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <label>Products</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Service_Description__c.field-meta.xml
<CustomField>
    <fullName>Service_Description__c</fullName>
    <label>Service Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Service_Outcomes__c.field-meta.xml
<CustomField>
    <fullName>Service_Outcomes__c</fullName>
    <label>Service Outcomes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Service_Prerequisites__c.field-meta.xml
<CustomField>
    <fullName>Service_Prerequisites__c</fullName>
    <label>Service Prerequisites</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Service_Title__c.field-meta.xml
<CustomField>
    <fullName>Service_Title__c</fullName>
    <label>Service Title</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Analytics/Reporting</fullName>
            </value>
            <value>
                <fullName>Configurations and Customisation</fullName>
            </value>
            <value>
                <fullName>Education/Training</fullName>
            </value>
            <value>
                <fullName>Flightpath Implementation Extras/Add Ons</fullName>
            </value>
            <value>
                <fullName>Integrations</fullName>
            </value>
            <value>
                <fullName>Strategic Engagements</fullName>
            </value>
            <value>
                <fullName>Upgrade and Migration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/User_Level__c.field-meta.xml
<CustomField>
    <fullName>User_Level__c</fullName>
    <label>User Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beginner</fullName>
            </value>
            <value>
                <fullName>Competent</fullName>
            </value>
            <value>
                <fullName>Expert</fullName>
            </value>
            <value>
                <fullName>Available for all levels</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/cspFlexPointsHandler.cls
public without sharing class cspFlexPointsHandler {
    @AuraEnabled(cacheable=false)
    public static Boolean requestAQuote(String description, String subject, String priority,
    String product, String serviceId, String entitlementId, String points, String accountId){
        if (entitlementId == null) {
            return false;
        }
        Savepoint sp = Database.setSavepoint();

        Service_Catalogues__c service = [SELECT Account_Journey_Stage__c, Hours_to_Deliver__c, Delivered_By__c, Location__c,
        Service_Description__c, Service_Outcomes__c, Service_Prerequisites__c, Service_Title__c,
        Service_Type__c, User_Level__c, Estimate_Required__c, Days_to_Deliver__c, Products__c, Delivery_Type__c, Division__c
        FROM Service_Catalogues__c WHERE Id =: serviceId];

        Case newCase = createCaseObj(description, subject, priority, product, serviceId, entitlementId, service, points, accountId);

        try {
            insert newCase;

            Case validateCase = [SELECT CaseNumber, Id, Subject FROM Case WHERE Id =: newCase.Id];
            if (validateCase != null){
                return true;
            } else {
                Database.rollback(sp);
                return false;
            }
        } catch(DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
            Database.rollback(sp);
            return false;
        }
    }

    @AuraEnabled(cacheable=false)
    public static Boolean createNewCase(String description, String subject, String priority,
    String product, String serviceId, String entitlementId, String accountId, String points){
        if (entitlementId == null) {
            return false;
        }
        Savepoint sp = Database.setSavepoint();

        Service_Catalogues__c service = [SELECT Account_Journey_Stage__c, Hours_to_Deliver__c, Delivered_By__c, Location__c,
        Service_Description__c, Service_Outcomes__c, Service_Prerequisites__c, Service_Title__c,
        Service_Type__c, User_Level__c, Estimate_Required__c, Days_to_Deliver__c, Products__c, Delivery_Type__c, Division__c
        FROM Service_Catalogues__c WHERE Id =: serviceId];

        Case newCase = createCaseObj(description, subject, priority, product, serviceId, entitlementId, service, points, accountId);
        try {
            insert newCase;

            Case validateCase = [SELECT CaseNumber, Id, Subject FROM Case WHERE Id =: newCase.Id];
            if (validateCase != null){
                return createTransactionRecord(validateCase.Id, accountId, Integer.valueOf(points), sp);
            } else {
                Database.rollback(sp);
                return false;
            }
        } catch(DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
            Database.rollback(sp);
            return false;
        }
    }

    private static Boolean createTransactionRecord(Id caseId, String accountId, Integer points, Savepoint sp){
        Date dateToday = Date.today();
        Id value = Id.valueOf(accountId);
        FlexPoints_Transactions__c flexPointsTransaction = new FlexPoints_Transactions__c(
            FlexPoint_Redemption_Case__c = caseId,
            Type__c = 'Redemption',
            Requested_Date__c = dateToday,
            Transaction_Status__c = 'Pending',
            Account__c = value,
            Points__c = points,
            Owner__c = UserInfo.getUserId()
        );
        try {
            insert flexPointsTransaction;

            FlexPoints_Transactions__c validateTransaction = [SELECT Id FROM FlexPoints_Transactions__c WHERE Id =: flexPointsTransaction.Id];
            if (validateTransaction != null) {
                return true;
            } else {
                Database.rollback(sp);
                return false;
            }
        } catch(DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
            Database.rollback(sp);
            return false;
        }
    }

    private static Case createCaseObj(String description, String subject, String priority,
    String product, String serviceId, String entitlementId, Service_Catalogues__c service, String points, String accountId) {
        Date dateToday = Date.today();
        return new Case(
            Status = service.Estimate_Required__c ? 'Estimate Required' : 'Pending',
            Description = description,
            Subject = subject,
            Origin = 'WebForm',
            Priority = priority,
            RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('FlexPoints Redemption').getRecordTypeId(),
            EntitlementId = Id.valueOf(entitlementId),
            RelatedProduct__c = product,
            Source__c = 'Support',
            CaseType__c = 'Feature request',

            Date_Requested__c = dateToday,
            Journey_Stage__c = service.Account_Journey_Stage__c,
            Points_Value__c = service.Estimate_Required__c ? null : Integer.valueOf(points),
            Hours_to_Deliver__c = service.Hours_to_Deliver__c,
            Delivered_By__c = service.Delivered_By__c,
            Location__c = service.Location__c,
            Service_Description__c = service.Service_Description__c,
            Service_Outcomes__c = service.Service_Outcomes__c,
            Service_Prerequisites__c = service.Service_Prerequisites__c,
            Service_Title__c = service.Service_Title__c,
            Service_Type__c = service.Service_Type__c,
            User_Level__c = service.User_Level__c,
            Account__c = accountId,
            AccountId = accountId,
            Delivery_Type__c = service.Delivery_Type__c,
            Days_to_Deliver__c = service.Days_to_Deliver__c,
            ProductMapped__c = service.Products__c,
            Division_FPT__c = service.Division__c
        );
    }

    @AuraEnabled(cacheable=false)
    public static FlexPoints_Transactions__c createQuoteApprovalTransaction(String accountId, Integer points, String owner, String caseId) {
        return createNewFlexPointsTransaction(accountId, points, owner, caseId, 'Pending', null);
    }

    @AuraEnabled(cacheable=false)
    public static FlexPoints_Transactions__c createCancellationFeeTransaction(String accountId, Integer points, String owner, String serviceName, String caseId) {
        return createNewFlexPointsTransaction(accountId, points, owner, caseId, 'Cancellation Fee', serviceName);
    }

    public static FlexPoints_Transactions__c createNewFlexPointsTransaction(String accountId, Integer points, String owner, String caseId, String status, String serviceName) {
        Date dateToday = Date.today();
        FlexPoints_Transactions__c flexPointsTransaction = new FlexPoints_Transactions__c(
            Type__c = 'Redemption',
            Requested_Date__c = dateToday,
            Transaction_Status__c = status,
            Points__c = points,
            Account__c = accountId,
            Expired__c = false,
            Owner__c = owner,
            FlexPoint_Redemption_Case__c = caseId,
            Cancelled_Service_Name__c = serviceName
        );
        insert flexPointsTransaction;
        return flexPointsTransaction;
    }

    @AuraEnabled(cacheable=false)
    public static void updateCase(String caseId, Integer points) {
        Case caseToUpdate = [SELECT Points_Value__c FROM Case WHERE Id =: caseId];
        caseToUpdate.Points_Value__c = points;
        caseToUpdate.Status = 'Pending';
        update caseToUpdate;
    }

    @AuraEnabled(cacheable=false)
    public static void rejectCase(String caseId) {
        Case caseToReject = [SELECT Status FROM Case WHERE Id =: caseId];
        caseToReject.Status = 'Rejected';
        update caseToReject;
    }
}