force-app/main/default/objects/FlexPoints_Transactions__c/FlexPoints_Transactions__c.object-meta.xml
<CustomObject>
    <label>FlexPoints Transactions</label>
    <nameField>
        <displayFormat>FPT-{0000}</displayFormat>
        <label>FlexPoints Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FlexPoints Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Lookup field so the permissions can be controlled independently from the account record. If roll ups are required then we can use managed package or apex class</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>FlexPoints Transactions</relationshipLabel>
    <relationshipName>FlexPoints_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Cancelled_Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Cancelled_Service_Name__c</fullName>
    <label>Cancelled Service Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/FlexPoint_Redemption_Case__c.field-meta.xml
<CustomField>
    <fullName>FlexPoint_Redemption_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The case that is associated with this particular redemption request.</description>
    <label>FlexPoint Redemption Case</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>FlexPoints Redemption</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>FlexPoints Transactions</relationshipLabel>
    <relationshipName>FlexPoints_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>FlexPoints_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <description>The number of points being added or subtracted from a customer&apos;s points balance. Value can be positive (+) or negative (-)</description>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Request_Subject__c.field-meta.xml
<CustomField>
    <fullName>Request_Subject__c</fullName>
    <description>Mirror of the subject field on the associated case record</description>
    <formula>FlexPoint_Redemption_Case__r.Subject</formula>
    <label>Request Subject</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Requested Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date of this transaction period. Either set manually or when generated through the integration</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>If the transaction has the &apos;Expired&apos; checkbox checked, the status is &apos;Expired&apos;

If the transaction type is NOT &apos;Redemption&apos;, the status is &apos;Top Up&apos;

Otherwise the status is = Transaction_Status__c</description>
    <formula>IF (Expired__c, &apos;Expired&apos;,
IF (NOT(ISPICKVAL(Type__c, &apos;Redemption&apos;)), &apos;Top Up&apos;,  TEXT(Transaction_Status__c)))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates the type of points this record is associated with.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Premier</fullName>
            </value>
            <value>
                <fullName>Advocacy</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Redemption</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Points__c/Points__c.object-meta.xml
<CustomObject>
    <label>Points</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Points Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Points__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Activity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telephone Reference</fullName>
            </value>
            <value>
                <fullName>Executive Quote</fullName>
            </value>
            <value>
                <fullName>Onsite Reference</fullName>
            </value>
            <value>
                <fullName>Webinar Presentation</fullName>
            </value>
            <value>
                <fullName>Case study and press release (written)</fullName>
            </value>
            <value>
                <fullName>Event Speaker</fullName>
            </value>
            <value>
                <fullName>Case study and press release (video and written)</fullName>
            </value>
            <value>
                <fullName>Host and speaker at an Access event on own premises</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Case Study</fullName>
                <isActive>false</isActive>
                <label>Case Study</label>
            </value>
            <value>
                <fullName>Case Study &amp; Press Release (Video &amp; Written)</fullName>
                <isActive>false</isActive>
                <label>Case Study &amp; Press Release (Video &amp; Written)</label>
            </value>
            <value>
                <fullName>Case Study &amp; Press Release (Written)</fullName>
                <isActive>false</isActive>
                <label>Case Study &amp; Press Release (Written)</label>
            </value>
            <value>
                <fullName>Host &amp; Speaker at Access Event on own Premises</fullName>
                <isActive>false</isActive>
                <label>Host &amp; Speaker at Access Event on own Premises</label>
            </value>
            <value>
                <fullName>Points Spend</fullName>
                <isActive>false</isActive>
                <label>Points Spend</label>
            </value>
            <value>
                <fullName>Sign - Up</fullName>
                <isActive>false</isActive>
                <label>Sign - Up</label>
            </value>
            <value>
                <fullName>Sign - Up (HCM)</fullName>
                <isActive>false</isActive>
                <label>Sign - Up (HCM)</label>
            </value>
            <value>
                <fullName>Sign-Up</fullName>
                <isActive>false</isActive>
                <label>Sign-Up</label>
            </value>
            <value>
                <fullName>Sign-Up (HCM)</fullName>
                <isActive>false</isActive>
                <label>Sign-Up (HCM)</label>
            </value>
            <value>
                <fullName>Site Reference</fullName>
                <isActive>false</isActive>
                <label>Site Reference</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/cspFlexPointsTransactionsHandler.cls
public without sharing class cspFlexPointsTransactionsHandler {
    @AuraEnabled(cacheable=false)
    public static List<Map<String, Object>> getFlexPointTransactions(String selectedAccountId, String statusType, Integer lmt, Integer ofst, Boolean isTransHistory) {
        String listQuery = 'SELECT Request_Subject__c, Status__c, Points__c, Owner__c, Owner__r.Name, FlexPoint_Redemption_Case__r.Id, Requested_Date__c, Name, Type__c, Cancelled_Service_Name__c FROM FlexPoints_Transactions__c WHERE Account__c =: selectedAccountId' + ' ';

        if (isTransHistory) {
            listQuery += 'AND (Start_Date__c <= TODAY OR Start_Date__c = NULL)' + ' ';
            listQuery += 'ORDER BY Requested_Date__c DESC NULLS LAST' + ' ';
            listQuery += String.format('LIMIT {0} OFFSET {1}', new List<Object>{lmt, ofst});
        } else {
            listQuery += 'AND Status__c =: statusType' + ' ';
            listQuery += 'ORDER BY Requested_Date__c DESC NULLS LAST';
        }

        String networkName = cspFlexPointsTransactionsHandler.getNetwork();
        String userId = UserInfo.getUserId();

        List<Map<String, Object>> transactionsResults = new List<Map<String, Object>>();

        for (FlexPoints_Transactions__c c: Database.query(listQuery)) {
            String owner = c.Owner__c != null ? (c.Owner__c.equals(userId) ? 'Me' : c.Owner__r.Name) : '';
            transactionsResults.add(new Map<String, Object>{
                'id' => c.Id,
                'subject' => c.Request_Subject__c,
                'points' => c.Points__c,
                'ref' => c.Name,
                'date' => c.Requested_Date__c,
                'status' => c.Status__c,
                'owner' => owner,
                'caseId' => c.FlexPoint_Redemption_Case__r.Id,
                'type' => c.Type__c,
                'cancelledService' => c.Cancelled_Service_Name__c
            });
        }

        return transactionsResults;
    }

    private static String getNetwork() {
        try {
            return [ SELECT UrlPathPrefix FROM Network WHERE Id = :Network.getNetworkId() ].UrlPathPrefix;
        } catch(QueryException e) {
            System.debug('Exception retrieving network id : ' + e.getMessage());
            return 'support';
        }
    }

    @AuraEnabled
    public static String getTransactionReference(String caseId) {
        return [SELECT Name FROM FlexPoints_Transactions__c WHERE FlexPoint_Redemption_Case__c =: caseId].Name;
    }
}