force-app/main/default/objects/FlexPoints_Transactions__c/FlexPoints_Transactions__c.object-meta.xml
<CustomObject>
    <label>FlexPoints Transactions</label>
    <nameField>
        <displayFormat>FPT-{0000}</displayFormat>
        <label>FlexPoints Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FlexPoints Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Lookup field so the permissions can be controlled independently from the account record. If roll ups are required then we can use managed package or apex class</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>FlexPoints Transactions</relationshipLabel>
    <relationshipName>FlexPoints_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End date of this transaction period. Either set manually or when generated through the integration</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Expired__c.field-meta.xml
<CustomField>
    <fullName>Expired__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used for when a transaction is an expiry calculation</description>
    <label>Expired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>FlexPoints_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <description>The number of points being added or subtracted from a customer&apos;s points balance. Value can be positive (+) or negative (-)</description>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Requested Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>If the transaction has the &apos;Expired&apos; checkbox checked, the status is &apos;Expired&apos;

If the transaction type is NOT &apos;Redemption&apos;, the status is &apos;Top Up&apos;

Otherwise the status is = Transaction_Status__c</description>
    <formula>IF (Expired__c, &apos;Expired&apos;,
IF (NOT(ISPICKVAL(Type__c, &apos;Redemption&apos;)), &apos;Top Up&apos;,  TEXT(Transaction_Status__c)))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <description>This field specifies the flexpoint transaction status</description>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Top Up</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Cancellation Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates the type of points this record is associated with.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Premier</fullName>
            </value>
            <value>
                <fullName>Advocacy</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Redemption</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Points__c/Points__c.object-meta.xml
<CustomObject>
    <label>Points</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Points Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Points__c/fields/Expired__c.field-meta.xml
<CustomField>
    <fullName>Expired__c</fullName>
    <formula>TODAY() &gt;  Expiry_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expired?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Points__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Activity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telephone Reference</fullName>
            </value>
            <value>
                <fullName>Executive Quote</fullName>
            </value>
            <value>
                <fullName>Onsite Reference</fullName>
            </value>
            <value>
                <fullName>Webinar Presentation</fullName>
            </value>
            <value>
                <fullName>Case study and press release (written)</fullName>
            </value>
            <value>
                <fullName>Event Speaker</fullName>
            </value>
            <value>
                <fullName>Case study and press release (video and written)</fullName>
            </value>
            <value>
                <fullName>Host and speaker at an Access event on own premises</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Case Study</fullName>
                <isActive>false</isActive>
                <label>Case Study</label>
            </value>
            <value>
                <fullName>Case Study &amp; Press Release (Video &amp; Written)</fullName>
                <isActive>false</isActive>
                <label>Case Study &amp; Press Release (Video &amp; Written)</label>
            </value>
            <value>
                <fullName>Case Study &amp; Press Release (Written)</fullName>
                <isActive>false</isActive>
                <label>Case Study &amp; Press Release (Written)</label>
            </value>
            <value>
                <fullName>Host &amp; Speaker at Access Event on own Premises</fullName>
                <isActive>false</isActive>
                <label>Host &amp; Speaker at Access Event on own Premises</label>
            </value>
            <value>
                <fullName>Points Spend</fullName>
                <isActive>false</isActive>
                <label>Points Spend</label>
            </value>
            <value>
                <fullName>Sign - Up</fullName>
                <isActive>false</isActive>
                <label>Sign - Up</label>
            </value>
            <value>
                <fullName>Sign - Up (HCM)</fullName>
                <isActive>false</isActive>
                <label>Sign - Up (HCM)</label>
            </value>
            <value>
                <fullName>Sign-Up</fullName>
                <isActive>false</isActive>
                <label>Sign-Up</label>
            </value>
            <value>
                <fullName>Sign-Up (HCM)</fullName>
                <isActive>false</isActive>
                <label>Sign-Up (HCM)</label>
            </value>
            <value>
                <fullName>Site Reference</fullName>
                <isActive>false</isActive>
                <label>Site Reference</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Points__c/recordTypes/Redemption.recordType-meta.xml
<RecordType>
    <fullName>Redemption</fullName>
    <active>false</active>
    <label>Redemption</label>
</RecordType>

force-app/main/default/classes/cspContactsHandlerTest.cls
@IsTest
private class cspContactsHandlerTest {

    @TestSetup
    static void makeData(){
        Account account = new Account(
            Name = 'Account Name',
            Highest_CSP_Level__c = ''
        );
        insert account;

        Contact contact = new Contact(
            LastName = 'TestMan',
            Email = 'testContactEmail@theaccessgroup.com',
            AccountId = account.Id
        );
        insert contact;

        User user = TestUtilities.createPortalUser('Customer Portal - Support User', contact.Id, 'test123p');
    }

    @IsTest Public Static Void GetPlan() {
        Id id = [SELECT Id FROM Account].Id;
        String plan = cspContactsHandler.getPlan(String.valueOf(id));
    }
    @IsTest Public Static Void GetCSM() {
        Id id = [SELECT Id FROM Account].Id;
        User plan = cspContactsHandler.getCSM(String.valueOf(id));
    }
    @IsTest Public Static Void GetAccountManager() {
        Id id = [SELECT Id FROM Account].Id;
        User plan = cspContactsHandler.getAccountManager(String.valueOf(id));
    }

    @IsTest
    public static void getFlexPoints() {

        User portalAccountOwner1 = TestUtilities.createUser('Support Admin', 'System Administrator', 'test123');
        System.runAs(portalAccountOwner1) {
            			//Create account
			Account portalAccount1 = new Account(Name = 'TestAccount', OwnerId = portalAccountOwner1.Id);
			insert portalAccount1;

            Account pgportalAccount1 = new Account(Name = 'pgTestAccount', OwnerId = portalAccountOwner1.Id);
			insert pgportalAccount1;
			// Create entitlement for case creation
			Entitlement ent = new Entitlement(Name = 'TestingEntitlement', 
										      AccountId = portalAccount1.Id, 
										      StartDate= Date.valueof(System.now().addDays(-2)), 
											  EndDate = Date.valueof(System.now().addYears(2)));
			insert ent;
			//Create contact
			Contact contact1 = new Contact(FirstName = 'Test', 
										   Lastname = 'McTesty', 
										   AccountId = portalAccount1.Id, 
										   Email = System.now().millisecond() + 'test@test.com');
			insert contact1;
			//Create our portal user
            User user1 = TestUtilities.createPortalUser('Customer Portal - Support User', contact1.Id, 'test123p');
           
            //Create Guadian contact
			Contact pgcontact1 = new Contact(FirstName = 'Test', 
										   Lastname = 'McGurdian', 
										   AccountId = portalAccount1.Id, 
										   Email = System.now().millisecond() + 'test@test.com');
			insert pgcontact1;
			//Create our portal user
            User pguser1 = TestUtilities.createPortalUser('Customer Portal - Support User', pgcontact1.Id, 'test456p');

            AccountContactRelation acr = new AccountContactRelation(
                AccountId = pgportalAccount1.Id,
                ContactId = pgcontact1.Id,
                roles = 'Points Guardian'
            );

            insert acr;

            Date requestedDate = Date.today();
            Date endDate = requestedDate.addDays(7);
            Date endDate2 = requestedDate.addDays(70);
            Id accountId = [SELECT Id FROM Account WHERE Name = 'TestAccount'].Id;

            Boolean IsNonPointUser =  cspContactsHandler.getIsNonPointsUser(accountId);
            system.assertEquals(true, IsNonPointUser);

            List<User> PointsGuardians = cspContactsHandler.getPointsGuardians(pgportalAccount1.Id);
            system.assertEquals(1, PointsGuardians.size());

            FlexPoints_Transactions__c flexPointTransactionPending = new FlexPoints_Transactions__c(
                Account__c = accountId,
                Transaction_Status__c = 'Pending',
                Type__c = 'Redemption',
                Points__c = 1000,
                Requested_Date__c = requestedDate,
                End_Date__c = endDate,
                Expired__c = false,
                Owner__c = UserInfo.getUserId()
            );
            insert flexPointTransactionPending;

            Decimal PointsEndSoon =  cspContactsHandler.getExpiringSoonPoints(accountId);
            system.assertEquals(0, PointsEndSoon);
    
            FlexPoints_Transactions__c flexPointTransactionConfirmed = new FlexPoints_Transactions__c(
                Account__c = accountId,
                Transaction_Status__c = 'Confirmed',
                Type__c = 'Redemption',
                Points__c =  1000,
                Expired__c = false,
                End_Date__c = endDate2,
                Requested_Date__c = requestedDate,
                Owner__c = UserInfo.getUserId()
            );
            insert flexPointTransactionConfirmed;
    
            FlexPoints_Transactions__c flexPointTransactionCancelled = new FlexPoints_Transactions__c(
                Account__c = accountId,
                Transaction_Status__c = 'Cancelled',
                Type__c = 'Redemption',
                Points__c = 1000,
                Requested_Date__c = requestedDate,
                End_Date__c = endDate,
                Expired__c = false,
                Owner__c = UserInfo.getUserId()
            );
            insert flexPointTransactionCancelled;
        

        system.runas(pguser1){
          Boolean isPointGuardian = cspContactsHandler.getIsPointsGuardian(pgportalAccount1.Id);

          system.assertEquals(true, isPointGuardian);


        }
    }

        FlexPoints_Transactions__c flexPointTransactionPending = [SELECT Account__c, Status__c, Type__c, Points__c, Requested_Date__c, End_Date__c FROM FlexPoints_Transactions__c WHERE Status__c = 'Pending'];
        FlexPoints_Transactions__c flexPointTransactionConfirmed = [SELECT Account__c, Status__c, Type__c, Points__c, Requested_Date__c, End_Date__c FROM FlexPoints_Transactions__c WHERE Status__c = 'Confirmed'];
        FlexPoints_Transactions__c flexPointTransactionCancelled = [SELECT Account__c, Status__c, Type__c, Points__c, Requested_Date__c, End_Date__c FROM FlexPoints_Transactions__c WHERE Status__c = 'Cancelled'];
        Id accountId = [SELECT Id FROM Account WHERE Name = 'TestAccount'].Id;
        
        Decimal totalAccural = 0;
        Decimal totalRedemptions = 2000;
        Decimal expiringSoon = 0;

        Map<String,Object> results = new Map<String, Object>{
            'id' => accountId,
            'availablePoints' => totalAccural - totalRedemptions,
            'totalConfirmed' => flexPointTransactionConfirmed.Points__c,
            'totalPending' => flexPointTransactionPending.Points__c,
            'currentBalance' => totalAccural - totalRedemptions,
            'expiringSoon' => expiringSoon
        };

        Map<String, Object> balances = cspContactsHandler.getFlexPoints(String.valueOf(accountId));

        System.assertEquals(JSON.serialize(results.get('totalConfirmed')), JSON.serialize(balances.get('totalConfirmed')));
        System.assertEquals(JSON.serialize(results.get('totalPending')), JSON.serialize(balances.get('totalPending')));
        System.assertEquals(JSON.serialize(results.get('availablePoints')), JSON.serialize(balances.get('availablePoints')));
        System.assertEquals(JSON.serialize(results.get('currentBalance')), JSON.serialize(balances.get('currentBalance')));
        System.assertEquals(JSON.serialize(results.get('expiringSoon')), JSON.serialize(balances.get('expiringSoon')));
        System.assertEquals(JSON.serialize(results.get('id')), JSON.serialize(balances.get('id')));
    }
    
}