force-app/main/default/objects/FlexPoints_Transactions__c/FlexPoints_Transactions__c.object-meta.xml
<CustomObject>
    <label>FlexPoints Transactions</label>
    <nameField>
        <displayFormat>FPT-{0000}</displayFormat>
        <label>FlexPoints Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FlexPoints Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Lookup field so the permissions can be controlled independently from the account record. If roll ups are required then we can use managed package or apex class</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>FlexPoints Transactions</relationshipLabel>
    <relationshipName>FlexPoints_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End date of this transaction period. Either set manually or when generated through the integration</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Expired__c.field-meta.xml
<CustomField>
    <fullName>Expired__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used for when a transaction is an expiry calculation</description>
    <label>Expired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <description>The number of points being added or subtracted from a customer&apos;s points balance. Value can be positive (+) or negative (-)</description>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <description>This field specifies the flexpoint transaction status</description>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Top Up</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Cancellation Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates the type of points this record is associated with.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Premier</fullName>
            </value>
            <value>
                <fullName>Advocacy</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Redemption</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Points__c/Points__c.object-meta.xml
<CustomObject>
    <label>Points</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Points Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Points__c/fields/Expired__c.field-meta.xml
<CustomField>
    <fullName>Expired__c</fullName>
    <formula>TODAY() &gt;  Expiry_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expired?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Points__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Activity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telephone Reference</fullName>
            </value>
            <value>
                <fullName>Executive Quote</fullName>
            </value>
            <value>
                <fullName>Onsite Reference</fullName>
            </value>
            <value>
                <fullName>Webinar Presentation</fullName>
            </value>
            <value>
                <fullName>Case study and press release (written)</fullName>
            </value>
            <value>
                <fullName>Event Speaker</fullName>
            </value>
            <value>
                <fullName>Case study and press release (video and written)</fullName>
            </value>
            <value>
                <fullName>Host and speaker at an Access event on own premises</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Case Study</fullName>
                <isActive>false</isActive>
                <label>Case Study</label>
            </value>
            <value>
                <fullName>Case Study &amp; Press Release (Video &amp; Written)</fullName>
                <isActive>false</isActive>
                <label>Case Study &amp; Press Release (Video &amp; Written)</label>
            </value>
            <value>
                <fullName>Case Study &amp; Press Release (Written)</fullName>
                <isActive>false</isActive>
                <label>Case Study &amp; Press Release (Written)</label>
            </value>
            <value>
                <fullName>Host &amp; Speaker at Access Event on own Premises</fullName>
                <isActive>false</isActive>
                <label>Host &amp; Speaker at Access Event on own Premises</label>
            </value>
            <value>
                <fullName>Points Spend</fullName>
                <isActive>false</isActive>
                <label>Points Spend</label>
            </value>
            <value>
                <fullName>Sign - Up</fullName>
                <isActive>false</isActive>
                <label>Sign - Up</label>
            </value>
            <value>
                <fullName>Sign - Up (HCM)</fullName>
                <isActive>false</isActive>
                <label>Sign - Up (HCM)</label>
            </value>
            <value>
                <fullName>Sign-Up</fullName>
                <isActive>false</isActive>
                <label>Sign-Up</label>
            </value>
            <value>
                <fullName>Sign-Up (HCM)</fullName>
                <isActive>false</isActive>
                <label>Sign-Up (HCM)</label>
            </value>
            <value>
                <fullName>Site Reference</fullName>
                <isActive>false</isActive>
                <label>Site Reference</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Points__c/recordTypes/Redemption.recordType-meta.xml
<RecordType>
    <fullName>Redemption</fullName>
    <active>false</active>
    <label>Redemption</label>
</RecordType>

force-app/main/default/classes/cspPointsExpiryHandlerTest.cls
@isTest
private class cspPointsExpiryHandlerTest {

    @TestSetup
    static void setUp(){
        // Account
        Account account = new Account(Name = 'Test Account');
        insert account;

        // Transactions
        insert new List<FlexPoints_Transactions__c> {
            // Accrual - end date in the future
            new FlexPoints_Transactions__c(Account__c = account.Id, Type__c = 'Manual', Transaction_Status__c = 'Confirmed', Points__c = 200, End_Date__c = DateTime.now().date().addDays(1)),
            // Accrual - end date in the past
            new FlexPoints_Transactions__c(Account__c = account.Id, Type__c = 'Manual', Transaction_Status__c = 'Confirmed', Points__c = 100, End_Date__c = DateTime.now().date().addDays(-1)),
            // Accrual - end date today
            new FlexPoints_Transactions__c(Account__c = account.Id, Type__c = 'Manual', Transaction_Status__c = 'Confirmed', Points__c = 50, End_Date__c = DateTime.now().date())
        };
    }

    @isTest
    private static void itShouldCreateAnExpiryTransactionWithNoRedemptions() {
        // Given we have an account with transactions
        // And a transaction ends today
        Account account = [SELECT Id FROM Account WHERE Name = 'Test Account'];

        // When the calculate points expiry method is invoked
        cspPointsExpiryHandler.calculatePointsExpiry(new List<Id> { account.Id });

        // Then I expect a transaction to be created of type redemption, status expired and points value 100
        FlexPoints_Transactions__c flexPointTransaction = [SELECT Points__c FROM FlexPoints_Transactions__c WHERE Type__c = 'Redemption' AND Expired__c = true];
        System.assertEquals(150, flexPointTransaction.Points__c);
    }

    @isTest
    private static void itShouldCreateAnExpiryTransactionWithRedemptions() {
        // Given we have an account with transactions
        // And a transaction ends today
        Account account = [SELECT Id FROM Account WHERE Name = 'Test Account'];

        // Transactions
        insert new List<FlexPoints_Transactions__c> {
            // Redemption
            new FlexPoints_Transactions__c(Account__c = account.Id, Type__c = 'Redemption', Transaction_Status__c = 'Redeemed', Points__c = 50)
        };

        // When the calculate points expiry method is invoked
        cspPointsExpiryHandler.calculatePointsExpiry(new List<Id> { account.Id });

        // Then I expect a transaction to be created of type redemption, status expired and points value 100
        FlexPoints_Transactions__c flexPointTransaction = [SELECT Points__c FROM FlexPoints_Transactions__c WHERE Type__c = 'Redemption' AND Expired__c = true];
        System.assertEquals(100, flexPointTransaction.Points__c);
    }
}