force-app/main/default/objects/FlexPoints_Transactions__c/FlexPoints_Transactions__c.object-meta.xml
<CustomObject>
    <label>FlexPoints Transactions</label>
    <nameField>
        <displayFormat>FPT-{0000}</displayFormat>
        <label>FlexPoints Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FlexPoints Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Lookup field so the permissions can be controlled independently from the account record. If roll ups are required then we can use managed package or apex class</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>FlexPoints Transactions</relationshipLabel>
    <relationshipName>FlexPoints_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/FlexPoint_Redemption_Case__c.field-meta.xml
<CustomField>
    <fullName>FlexPoint_Redemption_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The case that is associated with this particular redemption request.</description>
    <label>FlexPoint Redemption Case</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>FlexPoints Redemption</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>FlexPoints Transactions</relationshipLabel>
    <relationshipName>FlexPoints_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>FlexPoints_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <description>The number of points being added or subtracted from a customer&apos;s points balance. Value can be positive (+) or negative (-)</description>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Requested Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>If the transaction has the &apos;Expired&apos; checkbox checked, the status is &apos;Expired&apos;

If the transaction type is NOT &apos;Redemption&apos;, the status is &apos;Top Up&apos;

Otherwise the status is = Transaction_Status__c</description>
    <formula>IF (Expired__c, &apos;Expired&apos;,
IF (NOT(ISPICKVAL(Type__c, &apos;Redemption&apos;)), &apos;Top Up&apos;,  TEXT(Transaction_Status__c)))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <description>This field specifies the flexpoint transaction status</description>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Top Up</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Cancellation Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates the type of points this record is associated with.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Premier</fullName>
            </value>
            <value>
                <fullName>Advocacy</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Redemption</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Points__c/Points__c.object-meta.xml
<CustomObject>
    <label>Points</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Points Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Points__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Activity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telephone Reference</fullName>
            </value>
            <value>
                <fullName>Executive Quote</fullName>
            </value>
            <value>
                <fullName>Onsite Reference</fullName>
            </value>
            <value>
                <fullName>Webinar Presentation</fullName>
            </value>
            <value>
                <fullName>Case study and press release (written)</fullName>
            </value>
            <value>
                <fullName>Event Speaker</fullName>
            </value>
            <value>
                <fullName>Case study and press release (video and written)</fullName>
            </value>
            <value>
                <fullName>Host and speaker at an Access event on own premises</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Case Study</fullName>
                <isActive>false</isActive>
                <label>Case Study</label>
            </value>
            <value>
                <fullName>Case Study &amp; Press Release (Video &amp; Written)</fullName>
                <isActive>false</isActive>
                <label>Case Study &amp; Press Release (Video &amp; Written)</label>
            </value>
            <value>
                <fullName>Case Study &amp; Press Release (Written)</fullName>
                <isActive>false</isActive>
                <label>Case Study &amp; Press Release (Written)</label>
            </value>
            <value>
                <fullName>Host &amp; Speaker at Access Event on own Premises</fullName>
                <isActive>false</isActive>
                <label>Host &amp; Speaker at Access Event on own Premises</label>
            </value>
            <value>
                <fullName>Points Spend</fullName>
                <isActive>false</isActive>
                <label>Points Spend</label>
            </value>
            <value>
                <fullName>Sign - Up</fullName>
                <isActive>false</isActive>
                <label>Sign - Up</label>
            </value>
            <value>
                <fullName>Sign - Up (HCM)</fullName>
                <isActive>false</isActive>
                <label>Sign - Up (HCM)</label>
            </value>
            <value>
                <fullName>Sign-Up</fullName>
                <isActive>false</isActive>
                <label>Sign-Up</label>
            </value>
            <value>
                <fullName>Sign-Up (HCM)</fullName>
                <isActive>false</isActive>
                <label>Sign-Up (HCM)</label>
            </value>
            <value>
                <fullName>Site Reference</fullName>
                <isActive>false</isActive>
                <label>Site Reference</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Points__c/recordTypes/Redemption.recordType-meta.xml
<RecordType>
    <fullName>Redemption</fullName>
    <active>false</active>
    <label>Redemption</label>
</RecordType>

force-app/main/default/classes/CaseTriggerHandlerTest.cls
@isTest(SeeAllData=false)
public with sharing class CaseTriggerHandlerTest {
    @isTest
    private static void cases() {
        Case thisCase = TestUtilities.getCase();
        insert thisCase;

        Test.startTest();

        CaseTriggerHandler thisCaseTriggerHandler = new CaseTriggerHandler();
        System.assertEquals(0, thisCaseTriggerHandler.cases.size());

        thisCaseTriggerHandler.cases.add(thisCase);
        System.assertEquals(1, thisCaseTriggerHandler.cases.size());
        System.assertEquals(thisCase, thisCaseTriggerHandler.cases[0]);

        Test.stopTest();
    }

    @isTest
    private static void oldCasesMap() {
        Case thisCase = TestUtilities.getCase();
        insert thisCase;

        Test.startTest();
        
        CaseTriggerHandler thisCaseTriggerHandler = new CaseTriggerHandler();
        System.assertEquals(0, thisCaseTriggerHandler.oldCasesMap.size());

        thisCaseTriggerHandler.oldCasesMap.put(thisCase.Id, thisCase);
        System.assertEquals(1, thisCaseTriggerHandler.oldCasesMap.size());
        System.assert(thisCaseTriggerHandler.oldCasesMap.containsKey(thisCase.Id));
        System.assertEquals(thisCase, thisCaseTriggerHandler.oldCasesMap.get(thisCase.Id));

        Test.stopTest();
    }

    @isTest
    private static void afterCaseUpdate() {
        User portalAccountOwner1 = TestUtilities.createUser('Support Admin', 'System Administrator', 'test123');

        System.runAs(portalAccountOwner1) {
            Case thisCase = new Case(
                Status = 'Support Outstanding',
                Description = 'Description',
                Subject = 'Subject',
                Origin = 'Web',
                Priority = '3',
                RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('FlexPoints Redemption').getRecordTypeId(),
                RelatedProduct__c = 'Access Approve',
                Source__c = 'Support',
                CaseType__c = 'Feature request',
                Points_Estimate__c = 200
            );
            insert thisCase;
    
            List<Case> caseList = new List<Case>();
            caseList.add(thisCase);


            //Create account
			Account portalAccount1 = new Account(Name = 'TestAccount', OwnerId = portalAccountOwner1.Id);
			insert portalAccount1;

            Date requestedDate = Date.today();
            FlexPoints_Transactions__c flexPointTransactionPending = new FlexPoints_Transactions__c(
                Account__c = portalAccount1.Id,
                Transaction_Status__c = 'Pending',
                Type__c = 'Redemption',
                Points__c = 1000,
                Requested_Date__c = requestedDate,
                FlexPoint_Redemption_Case__c = thisCase.Id,
                Owner__c = UserInfo.getUserId()
            );
            insert flexPointTransactionPending;

            CaseTriggerHandler.afterCaseUpdate(caseList);

            FlexPoints_Transactions__c flexPointTransaction = [SELECT Transaction_Status__c, Status__c FROM FlexPoints_Transactions__c LIMIT 1];
            System.assertEquals(String.valueOf(thisCase.Status), flexPointTransaction.Status__c);
            System.assertEquals(String.valueOf(thisCase.Status), flexPointTransaction.Transaction_Status__c);
        }
    }

    @isTest
    private static void CaseTriggerHandler() {

        Test.startTest();

        CaseTriggerHandler thisCaseTriggerHandler = new CaseTriggerHandler();
        System.assertNotEquals(null, thisCaseTriggerHandler);

        Test.stopTest();
    }

    @isTest
    private static void getInstance() {
        CaseTriggerHandler.disableCaseTrigger = true;

        Case thisCase = TestUtilities.getCase();
        insert thisCase;

        List<Case> cases = new List<Case>();

        Map<Id, Case> oldCasesMap = new Map<Id, Case>();

        Test.startTest();
        
        CaseTriggerHandler thisCaseTriggerHandler = CaseTriggerHandler.getInstance(null, null);

        System.assertEquals(0, thisCaseTriggerHandler.cases.size());
        System.assertEquals(0, thisCaseTriggerHandler.oldCasesMap.size());

        thisCaseTriggerHandler = CaseTriggerHandler.getInstance(cases, oldCasesMap);

        System.assertEquals(0, thisCaseTriggerHandler.cases.size());
        System.assertEquals(0, thisCaseTriggerHandler.oldCasesMap.size());

        cases.add(thisCase);

        oldCasesMap.put(thisCase.Id, thisCase);

        thisCaseTriggerHandler = CaseTriggerHandler.getInstance(cases, oldCasesMap);

        System.assertEquals(cases.size(), thisCaseTriggerHandler.cases.size());
        System.assertEquals(cases[0], thisCaseTriggerHandler.cases[0]);
        System.assertEquals(oldCasesMap.size(), thisCaseTriggerHandler.oldCasesMap.size());
        System.assertEquals(oldCasesMap.get(thisCase.Id), thisCaseTriggerHandler.oldCasesMap.get(thisCase.Id));
        
        Test.stopTest();
    }

  //  @isTest
    //Private Static Void LoopKillerTest()
   // {
        //Case[] CaseList;
        
    //    Case cas1 = new Case(Status ='Support Outstanding', Priority = '1', Origin = 'Email', Subject='TestCase', SuppliedEmail='Jack@Jack.com');
    //    insert cas1;
        //CaseList.Add(cas1);
     
     //   Case cas2 = new Case(Status ='Support Outstanding', Priority = '1', Origin = 'Email', Subject='TestCase', SuppliedEmail='Jack@Jack.com');
     //   insert cas2;
        
     //   Case cas3 = new Case(Status ='Support Outstanding', Priority = '1', Origin = 'Email', Subject='TestCase', SuppliedEmail='Jack@Jack.com');
     //   insert cas3;
        
     //   Case cas4 = new Case(Status ='Support Outstanding', Priority = '1', Origin = 'Email', Subject='TestCase', SuppliedEmail='Jack@Jack.com');
     //   insert cas4;
        
     //   try{
     //  Case cas5 = new Case(Status ='Support Outstanding', Priority = '1', Origin = 'Email', Subject='TestCase', SuppliedEmail='Jack@Jack.com');
     //   insert cas5;
     //   }
     //   catch(exception e)
     //   {
     //       system.debug('Insert Case failed Due To Validation');
     //   }
     //   System.assertEquals(4, [SELECT count() FROM Case]);
  //  }
   
}