force-app/main/default/objects/FlexPoints_Transactions__c/FlexPoints_Transactions__c.object-meta.xml
<CustomObject>
    <label>FlexPoints Transactions</label>
    <nameField>
        <displayFormat>FPT-{0000}</displayFormat>
        <label>FlexPoints Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FlexPoints Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Started__c.field-meta.xml
<CustomField>
    <fullName>Started__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field determines whether or not the transaction has commenced based on the start date.</description>
    <label>Started</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/cspPointsCommencementHandler.cls
public without sharing class cspPointsCommencementHandler {
    
    @InvocableMethod(label='Calculate when transactions have started')
    public static void calculatePointsStarted(List<Id> flexPointIds){
        List<FlexPoints_Transactions__c> transactions = new List<FlexPoints_Transactions__c>();
        for (Id flexPointId: flexPointIds) {
            transactions.add(new FlexPoints_Transactions__c(
                Id = flexPointId,
                Started__c = true
            ));
        }
        update transactions;
    }
}