force-app/main/default/objects/FlexPoints_Transactions__c/FlexPoints_Transactions__c.object-meta.xml
<CustomObject>
    <label>FlexPoints Transactions</label>
    <nameField>
        <displayFormat>FPT-{0000}</displayFormat>
        <label>FlexPoints Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FlexPoints Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Lookup field so the permissions can be controlled independently from the account record. If roll ups are required then we can use managed package or apex class</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>FlexPoints Transactions</relationshipLabel>
    <relationshipName>FlexPoints_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End date of this transaction period. Either set manually or when generated through the integration</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Expired__c.field-meta.xml
<CustomField>
    <fullName>Expired__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used for when a transaction is an expiry calculation</description>
    <label>Expired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <description>The number of points being added or subtracted from a customer&apos;s points balance. Value can be positive (+) or negative (-)</description>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FlexPoints_Transactions__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates the type of points this record is associated with.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Premier</fullName>
            </value>
            <value>
                <fullName>Advocacy</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Redemption</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Points__c/Points__c.object-meta.xml
<CustomObject>
    <label>Points</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Points Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Points__c/fields/Expired__c.field-meta.xml
<CustomField>
    <fullName>Expired__c</fullName>
    <formula>TODAY() &gt;  Expiry_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expired?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Points__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Activity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telephone Reference</fullName>
            </value>
            <value>
                <fullName>Executive Quote</fullName>
            </value>
            <value>
                <fullName>Onsite Reference</fullName>
            </value>
            <value>
                <fullName>Webinar Presentation</fullName>
            </value>
            <value>
                <fullName>Case study and press release (written)</fullName>
            </value>
            <value>
                <fullName>Event Speaker</fullName>
            </value>
            <value>
                <fullName>Case study and press release (video and written)</fullName>
            </value>
            <value>
                <fullName>Host and speaker at an Access event on own premises</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Case Study</fullName>
                <isActive>false</isActive>
                <label>Case Study</label>
            </value>
            <value>
                <fullName>Case Study &amp; Press Release (Video &amp; Written)</fullName>
                <isActive>false</isActive>
                <label>Case Study &amp; Press Release (Video &amp; Written)</label>
            </value>
            <value>
                <fullName>Case Study &amp; Press Release (Written)</fullName>
                <isActive>false</isActive>
                <label>Case Study &amp; Press Release (Written)</label>
            </value>
            <value>
                <fullName>Host &amp; Speaker at Access Event on own Premises</fullName>
                <isActive>false</isActive>
                <label>Host &amp; Speaker at Access Event on own Premises</label>
            </value>
            <value>
                <fullName>Points Spend</fullName>
                <isActive>false</isActive>
                <label>Points Spend</label>
            </value>
            <value>
                <fullName>Sign - Up</fullName>
                <isActive>false</isActive>
                <label>Sign - Up</label>
            </value>
            <value>
                <fullName>Sign - Up (HCM)</fullName>
                <isActive>false</isActive>
                <label>Sign - Up (HCM)</label>
            </value>
            <value>
                <fullName>Sign-Up</fullName>
                <isActive>false</isActive>
                <label>Sign-Up</label>
            </value>
            <value>
                <fullName>Sign-Up (HCM)</fullName>
                <isActive>false</isActive>
                <label>Sign-Up (HCM)</label>
            </value>
            <value>
                <fullName>Site Reference</fullName>
                <isActive>false</isActive>
                <label>Site Reference</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Points__c/recordTypes/Redemption.recordType-meta.xml
<RecordType>
    <fullName>Redemption</fullName>
    <active>false</active>
    <label>Redemption</label>
</RecordType>

force-app/main/default/classes/cspPointsExpiryHandler.cls
public without sharing class cspPointsExpiryHandler {

    @InvocableMethod(label='Calculate Points Expiry')
    public static void calculatePointsExpiry(List<Id> accountIds){

        Map<Id, Map<String,Integer>> accountBalances = new Map<Id, Map<String,Integer>>();

        // Total Accruals
        for (AggregateResult ar : [SELECT
                                    Account__c,
                                    SUM(Points__c) Accruals
                                    FROM FlexPoints_Transactions__c
                                    WHERE Account__c IN: accountIds
                                    AND Type__c != 'Redemption'
                                    AND End_Date__c <= TODAY
                                    GROUP BY Account__c])
        {
            Map<String, Integer> balances = new Map<String, Integer> {
                'Accruals' => Integer.valueOf(ar.get('Accruals'))
            };

            accountBalances.put(Id.valueOf(String.valueOf(ar.get('Account__c'))), balances);
        }

        // Total Redemptions
        for (AggregateResult ar : [SELECT
                                    Account__c,
                                    SUM(Points__c) Redemptions
                                    FROM FlexPoints_Transactions__c
                                    WHERE Account__c IN: accountIds
                                    AND Type__c = 'Redemption'
                                    GROUP BY Account__c])
        {
            Id accountId = Id.valueOf(String.valueOf(ar.get('Account__c')));

            if (accountBalances.containsKey(accountId)) {
                Map<String, Integer> balances = accountBalances.get(accountId);
                balances.put('Redemptions', Integer.valueOf(ar.get('Redemptions')));
            }
        }

        // List of expiry transactions
        List<FlexPoints_Transactions__c> toInsert = new List<FlexPoints_Transactions__c>();

        for (Id accountId : accountBalances.keySet())
        {
            Map<String, Integer> balances = accountBalances.get(accountId);
            Integer accruals = balances.get('Accruals');
            Integer redemptions = balances.get('Redemptions') != null ? balances.get('Redemptions') : 0;

            // Calculate expiry points for account
            if (redemptions < accruals) {
                FlexPoints_Transactions__c flexPointTransaction = new FlexPoints_Transactions__c(
                    Account__c = accountId,
                    Points__c = accruals - redemptions,
                    Type__c = 'Redemption',
                    Expired__c = true
                );

                toInsert.add(flexPointTransaction);
            }
        }

        if (!toInsert.isEmpty()) {
            insert toInsert;
        }
    }
}