force-app/main/default/objects/Entitlement_Process__c/Entitlement_Process__c.object-meta.xml
<CustomObject>
    <description>Holds the current Entitlement Process&apos;s</description>
    <label>Entitlement Process</label>
    <nameField>
        <label>Entitlement Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entitlement Process&apos;s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Entitlement_Process__c/fields/Proccess_ID__c.field-meta.xml
<CustomField>
    <fullName>Proccess_ID__c</fullName>
    <label>Proccess ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KCS_Level__c/KCS_Level__c.object-meta.xml
<CustomObject>
    <description>This holds the KCS Level of the User</description>
    <label>KCS Level</label>
    <nameField>
        <label>KCS Level And User</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KCS Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KCS_Level__c/fields/KCS_Level__c.field-meta.xml
<CustomField>
    <fullName>KCS_Level__c</fullName>
    <description>The Level of the KCS User</description>
    <label>KCS Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Ready</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Expert</fullName>
            </value>
            <value>
                <fullName>Master</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KCS_Level__c/fields/KCS_User__c.field-meta.xml
<CustomField>
    <fullName>KCS_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The KCS User</description>
    <label>KCS User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>KCS_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KCS_Level__c/fields/Key_Field__c.field-meta.xml
<CustomField>
    <fullName>Key_Field__c</fullName>
    <description>This field stops duplicates</description>
    <label>Key Field</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Product_Routing__c.field-meta.xml
<CustomField>
    <fullName>Product_Routing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Routing</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ProductRouting__c.Division__c</field>
            <operation>equals</operation>
            <valueField>$Source.Division__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ProductRouting__c</referenceTo>
    <relationshipLabel>Knowledge</relationshipLabel>
    <relationshipName>Knowledge</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/recordTypes/KCS.recordType-meta.xml
<RecordType>
    <fullName>KCS</fullName>
    <active>true</active>
    <description>KCS Record Type</description>
    <label>KCS</label>
</RecordType>

force-app/main/default/objects/Product_Number__c/Product_Number__c.object-meta.xml
<CustomObject>
    <description>List of Product Numbers used by the Product Routing table to enable mapping of entitlements</description>
    <label>Product Number</label>
    <nameField>
        <label>Product Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Number__c/fields/Product_Routing__c.field-meta.xml
<CustomField>
    <fullName>Product_Routing__c</fullName>
    <label>Product Routing</label>
    <referenceTo>ProductRouting__c</referenceTo>
    <relationshipLabel>Product Numbers</relationshipLabel>
    <relationshipName>Product_Numbers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProductRange__c/ProductRange__c.object-meta.xml
<CustomObject>
    <label>Product Range</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Ranges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductRouting__c/ProductRouting__c.object-meta.xml
<CustomObject>
    <label>Product Routing</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Routings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductRouting__c/fields/Classic_Entitlement_Process__c.field-meta.xml
<CustomField>
    <fullName>Classic_Entitlement_Process__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to denote the classic entitlement SLA</description>
    <label>Classic Entitlement Process</label>
    <referenceTo>Entitlement_Process__c</referenceTo>
    <relationshipLabel>Product Routings</relationshipLabel>
    <relationshipName>Product_Routings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/Essential_Entitlement_Process__c.field-meta.xml
<CustomField>
    <fullName>Essential_Entitlement_Process__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Essential Entitlement Process</label>
    <referenceTo>Entitlement_Process__c</referenceTo>
    <relationshipLabel>Product Routings (Essential Entitlement Process)</relationshipLabel>
    <relationshipName>Essential_Product_Routings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/Premier_Entitlement_Process__c.field-meta.xml
<CustomField>
    <fullName>Premier_Entitlement_Process__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premier Entitlement Process</label>
    <referenceTo>Entitlement_Process__c</referenceTo>
    <relationshipLabel>Product Routings (Premier Entitlement Process)</relationshipLabel>
    <relationshipName>Premier_Product_Routings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/Product_Division__c.field-meta.xml
<CustomField>
    <fullName>Product_Division__c</fullName>
    <label>Product Division</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Division</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/Related_Product_Range__c.field-meta.xml
<CustomField>
    <fullName>Related_Product_Range__c</fullName>
    <label>Related Product Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/Standard_Entitlement_Process__c.field-meta.xml
<CustomField>
    <fullName>Standard_Entitlement_Process__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Standard Entitlement Process</label>
    <referenceTo>Entitlement_Process__c</referenceTo>
    <relationshipLabel>Product Routings (Standard Entitlement Process)</relationshipLabel>
    <relationshipName>Standard_Product_Routings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Contract_Lines__c/Service_Contract_Lines__c.object-meta.xml
<CustomObject>
    <description>A list of Service Contract products to be used to generate entitlements</description>
    <label>Service Contract Line</label>
    <nameField>
        <label>Line Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Contract Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Contract_Lines__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Line End Date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Contract_Lines__c/fields/Line_Status__c.field-meta.xml
<CustomField>
    <fullName>Line_Status__c</fullName>
    <label>Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Dead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Contract_Lines__c/fields/Plan_Product_Number__c.field-meta.xml
<CustomField>
    <fullName>Plan_Product_Number__c</fullName>
    <label>Plan Product Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Contract_Lines__c/fields/Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>Plan_Type__c</fullName>
    <label>Plan Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Contract_Lines__c/fields/Product_Number__c.field-meta.xml
<CustomField>
    <fullName>Product_Number__c</fullName>
    <description>Nominal Product Number</description>
    <label>Product Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Contract_Lines__c/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <description>Service Contract Link</description>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Service Contract Lines</relationshipLabel>
    <relationshipName>Service_Contract_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Contract_Lines__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Line Start Date</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TestUtilities.cls
@isTest(SeeAllData=false)
public with sharing class TestUtilities {
  static string ClassicEntProccess = 'Classic Entitlement';
  static string StandardEntProccess = 'Standard Entitlement';
  static string EssentialEntProccess = 'Essentials Entitlement';
  static string PremierEntProccess = 'Premier Entitlement';

  public static Account getAccount() {
    Account thisAccount = new Account();
    thisAccount.Name = 'Name-' + Crypto.getRandomInteger();
    return thisAccount;
  }

  public static Asset getAsset(Id accountId) {
    Asset thisAsset = new Asset();
    thisAsset.Name = 'Name-' + Crypto.getRandomInteger();
    thisAsset.AccountId = accountId;

    return thisAsset;
  }

  public static ProductRouting__c GetProductRouting(
    string product,
    string ProdNum
  ) {
    ProductRouting__c prc = new ProductRouting__c(
      Name = product,
      Classic_Entitlement_Process__c = GetSlaProccessID(ClassicEntProccess),
      Essential_Entitlement_Process__c = GetSlaProccessID(EssentialEntProccess),
      Standard_Entitlement_Process__c = GetSlaProccessID(StandardEntProccess),
      Premier_Entitlement_Process__c = GetSlaProccessID(PremierEntProccess),
      Related_Product_Range__c = product,
      Product_Division__c = 'SCS'
    );
    insert prc;

    Product_Number__c Pnumb = new Product_Number__c(
      name = ProdNum,
      Product_Routing__c = prc.id
    );

    insert Pnumb;

    return prc;
  }

  public static ServiceContract GetServiceContract(Account acc) {
    ServiceContract scc = new ServiceContract(
      AccountId = acc.id,
      Name = 'Name-' + Crypto.getRandomInteger(),
      StartDate = datetime.now().date() - 15,
      EndDate = datetime.now().addMonths(5).date(),
      SME_Contract_Status__c = 'Active'
    );

    insert scc;

    return scc;
  }

  public static Service_Contract_Lines__c GetServiceContractLines(
    ServiceContract Scc,
    string ProdNum
  ) {
    Service_Contract_Lines__c SCL = new Service_Contract_Lines__c(
      Name = 'Name-' + Crypto.getRandomInteger(),
      Start_Date__c = datetime.now().date() - 15,
      End_Date__c = datetime.now().addMonths(5).date(),
      Product_Number__c = decimal.valueOf(ProdNum),
      Line_Status__c = 'Active',
      Service_Contract__c = Scc.Id
    );

    insert SCL;
    return SCL;
  }

  public static Service_Contract_Lines__c GetServiceContractLinesCSP(
    ServiceContract Scc,
    string ProdNum,
    string PlanLevel
  ) {
    Service_Contract_Lines__c SCL = new Service_Contract_Lines__c(
      Name = 'Name-' + Crypto.getRandomInteger(),
      Start_Date__c = datetime.now().date() - 15,
      End_Date__c = datetime.now().addMonths(5).date(),
      Product_Number__c = 9999,
      Line_Status__c = 'Active',
      Service_Contract__c = Scc.Id,
      Plan_Type__c = 'Success Plan',
      Plan_Level__c = PlanLevel,
      Plan_Product_Number__c = ProdNum
    );
    insert SCL;

    return SCL;
  }

  private static id GetSlaProccessID(string Inname) {
    SlaProcess ProcID = [
      SELECT Id, NAME
      FROM Slaprocess
      WHERE name = :Inname AND IsVersionDefault = TRUE
    ];

    Entitlement_Process__c entproc = new Entitlement_Process__c(
      Name = Inname,
      Proccess_ID__c = ProcID.Id
    );

    insert entproc;

    return entproc.Id;
  }

  public static KCS_Level__c GetKCSLevel() {
    User newuser = new User();
    newuser = Internaladminuser();

    KCS_Level__c KCS = new KCS_Level__c();
    KCS.KCS_User__c = newuser.Id;
    KCS.Key_Field__c = 'Ready';

    insert KCS;

    return KCS;
  }

  public static User CreateUserComm() {
    User thisUser = new User();
    thisUser.Title = 'Mr';
    thisUser.FirstName = 'Roger';
    thisUser.LastName = 'Moore';
    thisUser.Email = 'RMoore@TheAccessGroup.com';
    thisUser.ProfileId = '00e58000000NgDx';

    return thisUser;
  }

  public static User internaladminuser() {
    User NewUser = new User(
      profileId = '00e58000000rpgN',
      Username = System.now().getTime() + 'InternalCase@test.com',
      Alias = 'RRTest',
      Email = 'Ryan.ReyonldsInternalCase@test.com',
      EmailEncodingKey = 'UTF-8',
      Title = 'Mr',
      Firstname = 'Ryan',
      Lastname = 'Reyonlds',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_GB',
      TimeZoneSidKey = 'Europe/London'
    );
    insert NewUser;

    return NewUser;
  }

  public static User createUser (String roleName,  String profileName,  String userAlias) {

    UserRole role = [SELECT Id FROM UserRole WHERE Name =: roleName LIMIT 1];
    Profile profile = [SELECT Id FROM Profile WHERE Name =: profileName LIMIT 1];

    User user = new User(
      Username = System.now().getTime() + 'test@user.com', 
      ProfileId = profile.Id, 
      UserRoleId = role.Id,
      Alias = userAlias, 
      Email = 'test123@test.com', 
      EmailEncodingKey = 'UTF-8', 
      Title = 'Mr',
      LastName = 'McTesty', 
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_GB',
      TimeZoneSidKey = 'Europe/London'
    );

    insert user;
    return user;
  }

  public static User createPortalUser (String portalProfileName, Id portalContactId, String userAlias) {

    Profile profile = [SELECT Id FROM Profile WHERE Name =: portalProfileName LIMIT 1];

    User user = new User(
      Username = System.now().getTime() + 'test@user.com', 
      ProfileId = profile.Id, 
      ContactId = portalContactId,
      Alias = userAlias, 
      Email = 'test123@test.com', 
      EmailEncodingKey = 'UTF-8', 
      Title = 'Mr',
      LastName = 'McTesty', 
      CommunityNickname = 'test12345' + System.now().getTime(), 
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_GB',
      TimeZoneSidKey = 'Europe/London'
    );

    insert user;
    return user;
  }

  public static Contact getContact() {
    Contact thisContact = new Contact();
    thisContact.FirstName = 'Chris';
    thisContact.LastName = 'Lewis';
    thisContact.Email = 'Chris.Lewis@accountech.co.uk';

    return thisContact;
  }

  public static Contact getContact(Account account) {
    Contact contact = getContact();
    contact.AccountId = account.id;

    return contact;
  }

  public static Case getCase() {
    Case thisCase = new Case();
    return thisCase;
  }

  public static CaseComment getCaseComment(Id parentId) {
    CaseComment thisCaseComment = new CaseComment();
    thisCaseComment.ParentId = parentId;

    return thisCaseComment;
  }

  public static Entitlement GetEntitlement(account AccountIdin) {
    Entitlement Ent = new Entitlement(
      Name = 'Classic Dimensions',
      Accountid = AccountIdin.id,
      StartDate = datetime.now().date() - 15,
      EndDate = datetime.now().addMonths(5).date(),
      AssociatedProductRange__c = 'Dimensions',
      SlaProcessId = [
        SELECT id, name, isVersionDefault
        FROM slaProcess
        WHERE
          isVersionDefault = TRUE
          AND isactive = TRUE
          AND name = 'Classic Entitlement'
        LIMIT 1
      ]
      .Id
    );

    insert ent;

    return ent;
  }

  public static Contract getContract(Id accountId) {
    Contract thisContract = new Contract();
    thisContract.AccountId = accountId;
    thisContract.ProductRange__c = 'Select HR';
    thisContract.PlanType__c = 'Standard';

    return thisContract;
  }

  public static Note getNote(Id parentId) {
    Note thisNote = new Note();
    thisNote.ParentId = parentId;
    thisNote.Title = 'Title-' + Crypto.getRandomInteger();

    return thisNote;
  }

  public static Product2 getProduct() {
    Product2 thisProduct = new Product2();
    thisProduct.Name = 'Name-' + Crypto.getRandomInteger();

    return thisProduct;
  }

  public static Knowledge__kav getArticleAsADraft(
    String title,
    String urlName
  ) {
    Knowledge__kav newArticle = new Knowledge__kav();
    newArticle.Title = title;
    newArticle.UrlName = urlName;
    return newArticle;
  }
}