force-app/main/default/objects/Curated_Collection__c/Curated_Collection__c.object-meta.xml
<CustomObject>
    <description>Link object to create collections of Knowledge articles related to one or more products</description>
    <label>Curated Collection</label>
    <nameField>
        <label>Curated Collection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curated Collections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Curated_Collection__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Used to denote the priority order in which this collection should be displayed in the community portal</description>
    <inlineHelpText>Higher priorities are displayed higher in the community portal</inlineHelpText>
    <label>Priority</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Curated_Collection__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <inlineHelpText>Select which products this collection relates to</inlineHelpText>
    <label>Products</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Curated_Collection__c/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <label>Short Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Curated_Collection__c/fields/Utility_Icon__c.field-meta.xml
<CustomField>
    <fullName>Utility_Icon__c</fullName>
    <description>The utility icon name to be displayed in the customer community portal</description>
    <inlineHelpText>Pick one of the utility icons found here www.lightningdesignsystem.com/icons/#utility</inlineHelpText>
    <label>Utility Icon</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Division__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge_Collection_Association__c/Knowledge_Collection_Association__c.object-meta.xml
<CustomObject>
    <description>Junction object for linking Knowledge articles with Curated Collections</description>
    <label>Knowledge Collection Association</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Collection Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Knowledge_Collection_Association__c/fields/Curated_Collection__c.field-meta.xml
<CustomField>
    <fullName>Curated_Collection__c</fullName>
    <label>Curated Collection</label>
    <referenceTo>Curated_Collection__c</referenceTo>
    <relationshipLabel>Knowledge Articles</relationshipLabel>
    <relationshipName>Knowledge_Collection_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Knowledge_Collection_Association__c/fields/Knowledge_Article__c.field-meta.xml
<CustomField>
    <fullName>Knowledge_Article__c</fullName>
    <label>Knowledge Article</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Curated Collections</relationshipLabel>
    <relationshipName>Knowledge_Collection_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Knowledge_Collection_Association__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Set the priority order of the article in this collection</description>
    <inlineHelpText>Set the priority order of the article in this collection</inlineHelpText>
    <label>Priority</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/cspCuratedCollectionHandlerTest.cls
@isTest(SeeAllData=false)
public with sharing class cspCuratedCollectionHandlerTest {
    @IsTest Public Static Void RetrieveCollections() {

        Knowledge__kav newArticle = TestUtilities.getArticleAsADraft('New title', 'new-url-name' + Crypto.getRandomInteger());
        newArticle.Division__c = 'Business Management';
        newArticle.Product__c = 'Access Approve';
        newArticle.Product_Features__c = 'Configuration';

        insert newArticle;
        String articleId = [SELECT KnowledgeArticleId FROM Knowledge__kav WHERE Id =: newArticle.Id].KnowledgeArticleId;
        KbManagement.PublishingService.publishArticle(articleId, true);

        Curated_Collection__c approveCollection= new Curated_Collection__c(Name = 'Collection Name',
                                                                            Products__c = 'Access Approve',
                                                                            Short_Description__c = 'Description goes here',
                                                                            Utility_Icon__c = 'activity',
                                                                            Priority__c = 10);
        insert approveCollection;

        Knowledge_Collection_Association__c association = new Knowledge_Collection_Association__c(Curated_Collection__c = approveCollection.Id,
                                                                                                    Knowledge_Article__c = newArticle.Id,
                                                                                                    Priority__c = 10);
        insert association;

        List<Map<String, Object>> collections = cspCuratedCollectionHandler.getCuratedCollections('Access Approve');
        System.assert(collections.size() == 1);
        System.assert(collections[0].get('title') == approveCollection.Name);
        System.assert(collections[0].get('articleCount') == 1);
        System.assert(collections[0].get('shortDescription') == approveCollection.Short_Description__c);
        System.assert(collections[0].get('icon') == approveCollection.Utility_Icon__c);
        System.assert(collections[0].get('priority') == approveCollection.Priority__c);

        List<Map<String, Object>> noCollections = cspCuratedCollectionHandler.getCuratedCollections('Not a product');
        System.assert(noCollections.size() == 0);
    }

    @IsTest Public Static Void GetCuratedArticles() {

        Knowledge__kav newArticle = TestUtilities.getArticleAsADraft('New title', 'new-url-name' + Crypto.getRandomInteger());
        newArticle.Division__c = 'Business Management';
        newArticle.Product__c = 'Access Approve';
        newArticle.Product_Features__c = 'Configuration';

        insert newArticle;
        String articleId = [SELECT KnowledgeArticleId FROM Knowledge__kav WHERE Id =: newArticle.Id].KnowledgeArticleId;
        KbManagement.PublishingService.publishArticle(articleId, true);

        Curated_Collection__c approveCollection = new Curated_Collection__c(Name = 'Collection Name',
                                                                            Products__c = 'Access Approve',
                                                                            Short_Description__c = 'Description goes here',
                                                                            Utility_Icon__c = 'activity',
                                                                            Priority__c = 10);
        insert approveCollection;

        Knowledge_Collection_Association__c association = new Knowledge_Collection_Association__c(Curated_Collection__c = approveCollection.Id,
                                                                                                    Knowledge_Article__c = newArticle.Id,
                                                                                                    Priority__c = 10);
        insert association;

        List<Map<String, Object>> articles = cspCuratedCollectionHandler.getCuratedArticles(approveCollection.Id);
        System.assert(articles.size() == 1);
        System.assert(articles[0].get('id') == newArticle.Id);
        System.assert(articles[0].get('title') == newArticle.Title);

        List<Map<String, Object>> noArticles = cspCuratedCollectionHandler.getCuratedArticles('wrongid');
        System.assert(noArticles.size() == 0);
    }

    @IsTest Public Static Void TestGetContactRegion() {
        String region = cspCuratedCollectionHandler.getContactRegion();
        System.assert(region == '');
    }
}