force-app/main/default/objects/Curated_Collection__c/Curated_Collection__c.object-meta.xml
<CustomObject>
    <description>Link object to create collections of Knowledge articles related to one or more products</description>
    <label>Curated Collection</label>
    <nameField>
        <label>Curated Collection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curated Collections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Curated_Collection__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Used to denote the priority order in which this collection should be displayed in the community portal</description>
    <inlineHelpText>Higher priorities are displayed higher in the community portal</inlineHelpText>
    <label>Priority</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Curated_Collection__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <inlineHelpText>Select which products this collection relates to</inlineHelpText>
    <label>Products</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Curated_Collection__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Multi select picklist field on curated collection for region</description>
    <inlineHelpText>Region(s) that the collection is available in. No value means the collection is available in all regions</inlineHelpText>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Community_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Curated_Collection__c/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <label>Short Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Curated_Collection__c/fields/Utility_Icon__c.field-meta.xml
<CustomField>
    <fullName>Utility_Icon__c</fullName>
    <description>The utility icon name to be displayed in the customer community portal</description>
    <inlineHelpText>Pick one of the utility icons found here www.lightningdesignsystem.com/icons/#utility</inlineHelpText>
    <label>Utility Icon</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Information_Article_Body__c.field-meta.xml
<CustomField>
    <fullName>Information_Article_Body__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Division__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region(s) that the article is available in</description>
    <inlineHelpText>Region(s) that the article is available in. No value means the article is available in all regions</inlineHelpText>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Community_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge_Collection_Association__c/Knowledge_Collection_Association__c.object-meta.xml
<CustomObject>
    <description>Junction object for linking Knowledge articles with Curated Collections</description>
    <label>Knowledge Collection Association</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Collection Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Knowledge_Collection_Association__c/fields/Curated_Collection__c.field-meta.xml
<CustomField>
    <fullName>Curated_Collection__c</fullName>
    <label>Curated Collection</label>
    <referenceTo>Curated_Collection__c</referenceTo>
    <relationshipLabel>Knowledge Articles</relationshipLabel>
    <relationshipName>Knowledge_Collection_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Knowledge_Collection_Association__c/fields/Knowledge_Article__c.field-meta.xml
<CustomField>
    <fullName>Knowledge_Article__c</fullName>
    <label>Knowledge Article</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Curated Collections</relationshipLabel>
    <relationshipName>Knowledge_Collection_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Knowledge_Collection_Association__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Set the priority order of the article in this collection</description>
    <inlineHelpText>Set the priority order of the article in this collection</inlineHelpText>
    <label>Priority</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/cspCuratedCollectionHandler.cls
public with sharing class cspCuratedCollectionHandler {
    
    @AuraEnabled(cacheable=true)
    public static List<Map<String, Object>> getCuratedCollections(String product) {
        String networkName = cspCuratedCollectionHandler.getNetwork();
        String contactRegion = getContactRegion();
        String userId = UserInfo.getUserId();
        String query = 'SELECT Name, Id, Products__c, Short_Description__c, Utility_Icon__c, Priority__c, Region__c,';

        if (String.isNotEmpty(contactRegion)) {
            query += ' (Select Id from Knowledge_Collection_Associations__r WHERE Knowledge_Article__r.Region__c = \'\' OR Knowledge_Article__r.Region__c includes (\'' + contactRegion + '\'))';
        } else {
            query += ' (Select Id from Knowledge_Collection_Associations__r)';
        }
        query += ' From Curated_Collection__c WHERE Products__c includes (\'' + product + '\')';
        if (String.isNotEmpty(contactRegion)) {
            query += ' AND (Region__c = \'\' OR Region__c includes (\'' + contactRegion + '\'))';
        }
        query += ' ORDER BY Priority__c';

        List<Curated_Collection__c> collectionList = Database.query(query);

        List<Map<String, Object>> collectionResults = new List<Map<String, Object>>();
        for (Curated_Collection__c c: collectionList) {
            collectionResults.add(new Map<String, Object>{
                'id' => c.Id,
                'title' => c.Name,
                'articleCount' => c.Knowledge_Collection_Associations__r.size(),
                'shortDescription' => c.Short_Description__c,
                'icon' => c.Utility_Icon__c,
                'priority' => c.Priority__c,
                'url' => String.format('/{0}/s/collection/{1}', new List<String>{networkName, c.Id})
            });
        }
        return collectionResults;
    }

    @AuraEnabled(cacheable=true)
    public static List<Map<String, Object>> getCuratedArticles(String collectionId) {
        String networkName = cspCuratedCollectionHandler.getNetwork();
        String userId = UserInfo.getUserId();
        String contactRegion = getContactRegion();
        String query = 'SELECT Knowledge_Article__r.ArticleNumber FROM Knowledge_Collection_Association__c where Curated_Collection__r.id=:collectionId ORDER BY Priority__c';
        List<Knowledge_Collection_Association__c> prioritisedArticles = Database.query(query);

        List<String> prioritisedArticleNumbers = new List<String>();
        for (Knowledge_Collection_Association__c article: prioritisedArticles) {
            prioritisedArticleNumbers.add(article.Knowledge_Article__r.ArticleNumber);
        }

        query = 'SELECT Title, ArticleNumber, ArticleTotalViewCount, LastPublishedDate, UrlName, Product__c, Product_Features__c, Information_Article_Body__c, Region__c FROM Knowledge__kav where ArticleNumber IN :prioritisedArticleNumbers';
        if (String.isNotEmpty(contactRegion)) {
            query += ' AND (Region__c = \'\' OR Region__c includes (\'' + contactRegion + '\'))';
        }
        List<Knowledge__kav> latestArticles = Database.query(query);


        List<Map<String, Object>> curatedArticles = new List<Map<String, Object>>();
        for (Knowledge_Collection_Association__c article: prioritisedArticles) {
            for (Knowledge__kav detail: latestArticles) {
                if (detail.ArticleNumber == article.Knowledge_Article__r.ArticleNumber) {
                    curatedArticles.add(new Map<String, Object>{
                        'id' => detail.Id,
                        'number' => detail.ArticleNumber,
                        'title' => detail.Title,
                        'views' => detail.ArticleTotalViewCount,
                        'dttm' => detail.LastPublishedDate,
                        'product' => detail.Product__c,
                        'productCategory' => detail.Product_Features__c,
                        'snippet' => detail.Information_Article_Body__c,
                        'url' => String.format('/{0}/s/article/{1}', new List<String>{networkName, detail.UrlName})
                    });
                }
            }
        }
        return curatedArticles;
    }

    private static String getNetwork() {
        try {
            return [ SELECT UrlPathPrefix FROM Network WHERE Id = :Network.getNetworkId() ].UrlPathPrefix;
        } catch(QueryException e) {
            System.debug('Exception retrieving network id : ' + e.getMessage());
            return 'support';
        }
    }

    @TestVisible private static String getContactRegion() {
        String userId = Userinfo.getUserid();
        User currentUser = Database.query('SELECT ContactId, Contact.Region__c FROM User WHERE Id =: userId');
        if (currentUser != null && String.isNotBlank(currentUser.ContactId) && String.isNotEmpty(currentUser.Contact.Region__c)) {
            String region = currentUser.Contact.Region__c;
            return currentUser.Contact.Region__c;
        }
        return '';
    }
}