force-app/main/default/objects/Service_Status_Update__c/Service_Status_Update__c.object-meta.xml
<CustomObject>
    <description>Object that handles records for Service Status Updates, these are displayed in the community either as a banner or on the service status page</description>
    <label>Service Status Update</label>
    <nameField>
        <displayFormat>ISU-{0000}</displayFormat>
        <label>Issue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Status Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Status_Update__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Detail of the issue</description>
    <inlineHelpText>Detail of the issue being experienced</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Service_Status_Update__c/fields/Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Date__c</fullName>
    <description>Date the issue was reported</description>
    <label>Open Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Status_Update__c/fields/Related_Product_Range__c.field-meta.xml
<CustomField>
    <fullName>Related_Product_Range__c</fullName>
    <label>Related Product Range</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Status_Update__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the issue</description>
    <inlineHelpText>Current status of the issue</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Working on Fix</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Status_Update__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The issue being experianced</description>
    <inlineHelpText>What is the issue</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Status_Update__c/fields/Visible__c.field-meta.xml
<CustomField>
    <fullName>Visible__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Visible</description>
    <label>Visible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CommunityAlerts.cls
/************************************************************************************
 * Class Name: CommunityAlerts
 * Purpose: Get the data from the object Service_Status_Update__c
 * Author: Chris Lewis
 * Release Version: 1
 * Release Code Coverage: Unknown
 * Notes: Please copy the template line below if you make changes, please mark the version change (Every push to Prod is a new version), Anotate any changed lines with your version and what was changed 
 * Also please ensure any test code is at least the same code coverage as the release code coverage.
 * This was originaly created by a 3rd party so missing annotations.
 * Changed By: YOURNAME Date: THISDATE Reason\Changes: YOUR REASON Version: PREV+1
 * *********************************************************************************/

public with sharing class CommunityAlerts {
    
@AuraEnabled  
   Public Static List<Service_Status_Update__c> GetCommunityAlerts()
    {
        List<Service_Status_Update__c> comalert = new List<Service_Status_Update__c>([select Title__c, Description__c from Service_Status_Update__c where Visible__c = true and recordtypeId = '0124I0000006RgqQAE']);
       return comalert;
    }
    @AuraEnabled  
       Public Static List<Service_Status_Update__c> GetServicePage()
    {
        List<Service_Status_Update__c> servicepage = new List<Service_Status_Update__c>([select Title__c, Description__c, Open_Date__c, Status__c from Service_Status_Update__c where Visible__c = true and recordtypeId = '0124I0000006RgrQAE']);
       return servicepage;
    }

    @AuraEnabled
    public static List<Service_Status_Update__c> GetServiceStatus(string product){
      try {
         List<Service_Status_Update__c> comalert = new List<Service_Status_Update__c>([select Title__c, Description__c, Related_Product_Range__c  from Service_Status_Update__c where Visible__c = true and recordtypeId = '0124I0000006RgqQAE' and related_product_Range__c includes (:product)]);          
         return comalert;
      } catch (Exception e) {
          throw new AuraHandledException(e.getMessage());
          return null;
       }
       return null;
    }

    @AuraEnabled
    public static List<Service_Status_Update__c> GetProductNotification(string product){
      try {
         List<Service_Status_Update__c> comalert = new List<Service_Status_Update__c>([select Title__c, Description__c, Related_Product_Range__c  from Service_Status_Update__c where Visible__c = true and recordtypeId = '0124I000000Qn2xQAC' and related_product_Range__c includes (:product)]);          
         return comalert;
      } catch (Exception e) {
          throw new AuraHandledException(e.getMessage());
          return null;
       }
       return null;
    }
    
    
}