force-app/main/default/objects/Service_Status_Update__c/Service_Status_Update__c.object-meta.xml
<CustomObject>
    <description>Object that handles records for Service Status Updates, these are displayed in the community either as a banner or on the service status page</description>
    <label>Service Status Update</label>
    <nameField>
        <displayFormat>ISU-{0000}</displayFormat>
        <label>Issue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Status Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Status_Update__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Detail of the issue</description>
    <inlineHelpText>Detail of the issue being experienced</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Service_Status_Update__c/fields/Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Date__c</fullName>
    <description>Date the issue was reported</description>
    <label>Open Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Status_Update__c/fields/Related_Product_Range__c.field-meta.xml
<CustomField>
    <fullName>Related_Product_Range__c</fullName>
    <label>Related Product Range</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Status_Update__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The issue being experianced</description>
    <inlineHelpText>What is the issue</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Status_Update__c/fields/Visible__c.field-meta.xml
<CustomField>
    <fullName>Visible__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Visible</description>
    <label>Visible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CommunityAlertsTest.cls
@IsTest 

public with sharing class CommunityAlertsTest {

    @AuraEnabled

@IsTest Public Static void GetAlertHeader()
    
{
Service_Status_Update__c cia = new Service_Status_Update__c();
    cia.Title__c = 'ALTO Services';
    cia.Description__c = 'Test';
    cia.Visible__c = TRUE;
    cia.recordtypeId = '0124I0000006RgqQAE';
    insert cia;

List<Service_Status_Update__c> Alert = (CommunityAlerts.GetCommunityAlerts());
    if(Alert.size() > 0)
    {
System.assertEquals('ALTO Services',Alert[0].Title__c);
    }
}

@IsTest Public Static void GetServicePage()
    //DateTime dt = DateTime.Now()
{
Service_Status_Update__c ssp = new Service_Status_Update__c();
    ssp.Title__c = 'ALTO Status';
    ssp.Description__c = 'Test';
    ssp.Open_Date__c = DateTime.Now().date();
    ssp.Visible__c = TRUE;
    ssp.recordtypeId = '0124I0000006RgrQAE';
    insert ssp;

List<Service_Status_Update__c> Alert = (CommunityAlerts.GetServicePage());
    if(Alert.size() > 0)
    {
System.assertEquals('ALTO Status',Alert[0].Title__c);
    }
}

@IsTest Public Static void GetServiceStatus()
    
{
Service_Status_Update__c css = new Service_Status_Update__c();
css.Title__c = 'ALTO Service';
css.Description__c = 'Test';
css.Related_Product_Range__c = 'Dimensions';
css.Visible__c = TRUE;
css.recordtypeId = '0124I0000006RgqQAE';
    insert css;

List<Service_Status_Update__c> Alert = (CommunityAlerts.GetServiceStatus('Dimensions'));
    if(Alert.size() > 0)
    {
System.assertEquals('ALTO Service',Alert[0].Title__c);
    }
}

@IsTest Public Static void GetProductNotification()
    
{
Service_Status_Update__c cpn = new Service_Status_Update__c();
cpn.Title__c = 'ALTO Product';
cpn.Description__c = 'Test';
cpn.Related_Product_Range__c = 'Dimensions';
cpn.Visible__c = TRUE;
cpn.recordtypeId = '0124I000000Qn2xQAC';
    insert cpn;

List<Service_Status_Update__c> Alert = (CommunityAlerts.GetProductNotification('Dimensions'));
    if(Alert.size() > 0)
    {
System.assertEquals('ALTO Product',Alert[0].Title__c);
    }
}

@IsTest Public Static void GetProductNotificationnull()
    
{
Service_Status_Update__c cpn = new Service_Status_Update__c();
cpn.Title__c = 'ALTO Product';
cpn.Description__c = 'Test';
cpn.Related_Product_Range__c = null;
cpn.Visible__c = TRUE;
cpn.recordtypeId = '0124I000000Qn2xQAC';
    insert cpn;

List<Service_Status_Update__c> Alert = (CommunityAlerts.GetProductNotification(null));
    if(Alert.size() > 0)
    {
System.assertEquals('ALTO Product',Alert[0].Title__c);
    }
}

 @IsTest   Public Static List<Service_Status_Update__c> GetCommunityAlerts()
    {
        List<Service_Status_Update__c> comalert = new List<Service_Status_Update__c>([select Title__c, Description__c from Service_Status_Update__c where Visible__c = true]);
       return comalert;
    }
    
}