force-app/main/default/objects/Service_Catalogues__c/Service_Catalogues__c.object-meta.xml
<CustomObject>
    <label>Services Catalogue</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Service Catalogue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services Catalogue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Catalogues__c/fields/Account_Journey_Stage__c.field-meta.xml
<CustomField>
    <fullName>Account_Journey_Stage__c</fullName>
    <label>Account Journey Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New to Product</fullName>
            </value>
            <value>
                <fullName>In first year of using product</fullName>
            </value>
            <value>
                <fullName>Been using the product for some time</fullName>
            </value>
            <value>
                <fullName>Applicable to all</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Delivered_By__c.field-meta.xml
<CustomField>
    <fullName>Delivered_By__c</fullName>
    <label>Delivered By</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Customer Success Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <label>Delivery Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bite Size</fullName>
            </value>
            <value>
                <fullName>Virtual Classroom</fullName>
            </value>
            <value>
                <fullName>Classroom</fullName>
            </value>
            <value>
                <fullName>1:1 Consulting</fullName>
            </value>
            <value>
                <fullName>1:Many Consulting</fullName>
            </value>
            <value>
                <fullName>Remote Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Estimate_Required__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Leave the Points Conversion field empty and check this box if this Service requires our team to estimate the effort per customer request.</inlineHelpText>
    <label>Estimate Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Remote</fullName>
            </value>
            <value>
                <fullName>Onsite</fullName>
            </value>
            <value>
                <fullName>Access Office Location</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Points_Conversion__c.field-meta.xml
<CustomField>
    <fullName>Points_Conversion__c</fullName>
    <label>Points Conversion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Premier_Only__c.field-meta.xml
<CustomField>
    <fullName>Premier_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Premier Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <label>Products</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Community_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Service_Description__c.field-meta.xml
<CustomField>
    <fullName>Service_Description__c</fullName>
    <label>Service Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Service_Outcomes__c.field-meta.xml
<CustomField>
    <fullName>Service_Outcomes__c</fullName>
    <label>Service Outcomes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Service_Prerequisites__c.field-meta.xml
<CustomField>
    <fullName>Service_Prerequisites__c</fullName>
    <label>Service Prerequisites</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Service_Title__c.field-meta.xml
<CustomField>
    <fullName>Service_Title__c</fullName>
    <label>Service Title</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Analytics/Reporting</fullName>
            </value>
            <value>
                <fullName>Configurations and Customisation</fullName>
            </value>
            <value>
                <fullName>Education/Training</fullName>
            </value>
            <value>
                <fullName>Flightpath Implementation Extras/Add Ons</fullName>
            </value>
            <value>
                <fullName>Integrations</fullName>
            </value>
            <value>
                <fullName>Strategic Engagements</fullName>
            </value>
            <value>
                <fullName>Upgrade and Migration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/User_Level__c.field-meta.xml
<CustomField>
    <fullName>User_Level__c</fullName>
    <label>User Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beginner</fullName>
            </value>
            <value>
                <fullName>Competent</fullName>
            </value>
            <value>
                <fullName>Expert</fullName>
            </value>
            <value>
                <fullName>Available for all levels</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/cspServiceCatalogueEntryHandler.cls
public with sharing class cspServiceCatalogueEntryHandler {
    @AuraEnabled(cacheable=true)
    public static List<Service_Catalogues__c> getServiceCatalogueEntries(String selectedAccId, String product, Integer lmt, Integer ofst, Boolean incrementLmt,
        String serviceType, String userLevel, String journeyLevel, String deliveryType, String deliveredBy, String location, Boolean premierOnly){
        if (incrementLmt) {
            ++lmt;
        }

        User currentUser = [SELECT ContactId FROM User WHERE Id =: Userinfo.getUserId()];
        List<String> entitledProducts = cspProductSelection.getFlatProductList(selectedAccId);

        String productList = '';
        for (Integer i = 0; i < entitledProducts.size(); i++) {
            productList += '\'' + entitledProducts.get(i) + '\'';
            if (i < entitledProducts.size() - 1) {
                productList += ',';
            }
        }

        if (entitledProducts.size() == 0 && String.isEmpty(product)) {
            return new List<Service_Catalogues__c>();
        }

        String listQuery = 'SELECT Service_Title__c, Service_Type__c, Service_Description__c, Points_Conversion__c, Premier_Only__c, Estimate_Required__c FROM Service_Catalogues__c WHERE Service_Title__c != null' + ' ';

        if (product != null && String.isNotBlank(product)) {
            listQuery += 'AND Products__c includes (\'' + product + '\') ';
        } else {
            listQuery += 'AND Products__c includes (' + productList + ') ';
        }

        if (String.isNotBlank(serviceType)) {
            listQuery += 'AND Service_Type__c includes (\'' + serviceType + '\') ';
        }

        if (String.isNotBlank(userLevel)) {
            listQuery += 'AND User_Level__c =: userLevel ';
        }

        if (String.isNotBlank(journeyLevel)) {
            listQuery += 'AND Account_Journey_Stage__c =: journeyLevel ';
        }

        if (String.isNotBlank(deliveryType)) {
            listQuery += 'AND Delivery_Type__c =: deliveryType ';
        }

        if (String.isNotBlank(deliveredBy)) {
            listQuery += 'AND Delivered_By__c includes (\'' + deliveredBy + '\') ';
        }

        if (String.isNotBlank(location)) {
            listQuery += 'AND Location__c =: location ';
        }

        if (premierOnly != null && premierOnly) {
            listQuery += 'AND Premier_Only__c =: premierOnly ';
        }

        if (currentUser != null && String.isNotBlank(currentUser.ContactId)) {
            Id contactId = currentUser.ContactId;
            String region = [SELECT Region__c FROM Contact WHERE Id =: contactId].Region__c;

            if (region != null && String.isNotBlank(region)) {
                listQuery += 'AND Region__c INCLUDES (:region) ';
            }
        } 

        listQuery += String.format('LIMIT {0} OFFSET {1}', new List<Object>{lmt, ofst});

        List<sObject> sobjList = Database.query(listQuery);
        return sobjList;
    }

    @AuraEnabled(cacheable=true)
    public static Service_Catalogues__c getServiceCatalogue(String serviceCatalogueId) {
        User currentUser = [SELECT ContactId FROM User WHERE Id =: Userinfo.getUserId()];

        String query = 'SELECT Service_Title__c, Service_Description__c, Points_Conversion__c, Premier_Only__c, Service_Prerequisites__c, Delivery_Type__c, Account_Journey_Stage__c, Service_Type__c, Service_Outcomes__c, Estimate_Required__c FROM Service_Catalogues__c WHERE  Id =: serviceCatalogueId' + ' ';

        if (currentUser != null && String.isNotBlank(currentUser.ContactId)) {
            Id contactId = currentUser.ContactId;
            String region = [SELECT Region__c FROM Contact WHERE Id =: contactId].Region__c;

            if (region != null && String.isNotBlank(region)) {
                query += 'AND Region__c INCLUDES (:region)';
            }
        }
        Service_Catalogues__c serviceCatalogue = Database.query(query);
        serviceCatalogue.Service_Type__c = serviceCatalogue.Service_Type__c.replaceAll(';', ', ');

        return serviceCatalogue;
    }

    @AuraEnabled(cacheable=true)
    public static Map<String, String> getRelatedProduct(String serviceCatalogueId, String selectedAccId){
        List<String> entitledProducts = cspProductSelection.getFlatProductList(selectedAccId);

        Service_Catalogues__c serviceCatalogue = [SELECT Products__c FROM Service_Catalogues__c WHERE Id =: serviceCatalogueId];
        List<String> products = serviceCatalogue.Products__c.split(';');

        Integer index = 0;
        String relatedProduct = '';
        
        if (products.size() > 0) {
            for (String product : products) {
                if (entitledProducts.contains(product)) {
                    relatedProduct = product;
                }
            }
        }

        return cspProductSelection.getProduct(relatedProduct, selectedAccId);
    }
}