force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Information_Article_Body__c.field-meta.xml
<CustomField>
    <fullName>Information_Article_Body__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Division__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Note__c/Release_Note__c.object-meta.xml
<CustomObject>
    <label>Release Note</label>
    <nameField>
        <label>Release Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Release Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release_Note__c/fields/Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Knowledge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Knowledge</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Release Notes</relationshipLabel>
    <relationshipName>Release_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release_Note__c/fields/Postponed__c.field-meta.xml
<CustomField>
    <fullName>Postponed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Postponed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Release_Note__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Note__c/fields/Release_Details__c.field-meta.xml
<CustomField>
    <fullName>Release_Details__c</fullName>
    <label>Release Details</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full program</fullName>
            </value>
            <value>
                <fullName>Service pack</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Workspace app</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Note__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Automated</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Note__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/cspReleaseNoteHandlerTest.cls
@isTest
public with sharing class cspReleaseNoteHandlerTest {
    @IsTest Public Static Void RetrieveCollections() {
        Knowledge__kav newArticle = TestUtilities.getArticleAsADraft('New title', 'new-url-name' + Crypto.getRandomInteger());
        newArticle.Information_Article_Body__c = 'New article';
        newArticle.Division__c = 'Business Management';
        newArticle.Product__c = 'Access Approve';
        insert newArticle;
        String articleId = [SELECT KnowledgeArticleId FROM Knowledge__kav WHERE Id =: newArticle.Id].KnowledgeArticleId;
        KbManagement.PublishingService.publishArticle(articleId, true);

        Release_Note__c note = new Release_Note__c();
        note.Version__c = '1.1.1';
        note.Product__c = 'Access Approve';
        note.Release_Date__c = Date.newInstance(1960, 2, 17);
        note.Knowledge__c = newArticle.Id;
        note.Type__c = 'Request';
        note.Postponed__c = false;
        note.Release_Details__c = 'Mobile';
        insert note;

        List<Map<String, Object>> releaseNotes = cspReleaseNoteHandler.getReleaseNotes('Access Approve', 10, 0);
        System.assert(releaseNotes.size() == 1);
        System.assert(releaseNotes[0].get('version') == '1.1.1');
        System.assert(releaseNotes[0].get('product') == 'Access Approve');
        System.assert(releaseNotes[0].get('releaseNotes') == 'New title');

        List<Map<String, Object>> noReleases = cspReleaseNoteHandler.getReleaseNotes('Not a product', 10, 0);
        System.assert(noReleases.size() == 0);
    }

    @IsTest Public Static Void TestGetContactRegion() {
        String region = cspReleaseNoteHandler.getContactRegion();
        System.assert(region == '');
    }
}