force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Featured__c.field-meta.xml
<CustomField>
    <fullName>Featured__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to determine whether a knowledge article should be displayed in the featured articles block in the support community</description>
    <inlineHelpText>Select this checkbox to mark the article as featured</inlineHelpText>
    <label>Featured</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Division__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/cspArticleProductMappingTest.cls
@isTest(SeeAllData=true)
public class cspArticleProductMappingTest {
    
    @isTest
    private static void processArticles() {
        Knowledge__kav newArticle = TestUtilities.getArticleAsADraft('New title', 'new-url-name' + Crypto.getRandomInteger());
        newArticle.Division__c = 'Business Management';
        newArticle.Product__c = 'Access Approve';
        newArticle.Product_Features__c = 'Configuration';
        newArticle.Featured__c = true;
        
        insert newArticle;
        String articleId = [SELECT KnowledgeArticleId FROM Knowledge__kav WHERE Id =: newArticle.Id].KnowledgeArticleId;
        KbManagement.PublishingService.publishArticle(articleId, true);

        Test.StartTest();
        cspArticleProductMapping noOpMapper = new cspArticleProductMapping('SELECT Id, KnowledgeArticleId, Title, Product__c, Division__c, (SELECT Id,toLabel(DataCategoryName),DataCategoryGroupName FROM DataCategorySelections) FROM Knowledge__kav WHERE publishStatus=\'online\' LIMIT 20', true);
        ID noOpBatch = Database.executeBatch(noOpMapper);

        cspArticleProductMapping mapper = new cspArticleProductMapping('SELECT Id, KnowledgeArticleId, Title, Product__c, Division__c, (SELECT Id,toLabel(DataCategoryName),DataCategoryGroupName FROM DataCategorySelections) FROM Knowledge__kav WHERE publishStatus=\'online\' LIMIT 20', false);
        ID batchprocessid = Database.executeBatch(mapper);
        Test.StopTest();
    }
}