force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Division__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductRouting__c/ProductRouting__c.object-meta.xml
<CustomObject>
    <label>Product Routing</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Routings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductRouting__c/fields/Product_Division__c.field-meta.xml
<CustomField>
    <fullName>Product_Division__c</fullName>
    <label>Product Division</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Division</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/Related_Product_Range__c.field-meta.xml
<CustomField>
    <fullName>Related_Product_Range__c</fullName>
    <label>Related Product Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/cspKnowledgeTest.cls
@isTest
public class cspKnowledgeTest {
    @isTest
    private static void getKnowledgeArticle() {
        Knowledge__kav newArticle = TestUtilities.getArticleAsADraft('New title', 'new-url-name' + Crypto.getRandomInteger());
        newArticle.Division__c = 'Business Management';
        newArticle.Product__c = 'Access Approve';
        newArticle.Product_Features__c = 'Configuration';
        
        ProductRouting__c pr = new ProductRouting__c(
            name = 'Access Approve',
            Related_Product_Range__c = 'Access Approve',
            Product_Division__c = 'FMS'
            
        );
        
        insert pr;

        insert newArticle;
        String articleId = [SELECT KnowledgeArticleId FROM Knowledge__kav WHERE Id =: newArticle.Id].KnowledgeArticleId;
        KbManagement.PublishingService.publishArticle(articleId, true);

        Map<String, Object> knowledgeResult = CspKnowledge.getKnowledgeArticle(newArticle.UrlName);

        System.assert(knowledgeResult != null);
        System.assert(knowledgeResult.get('Title') == newArticle.Title);
        System.assert(knowledgeResult.get('ProductName') == newArticle.Product__c);
    }
    @isTest
    private static void getKnowledgeArticleFail() {
        Knowledge__kav newArticle1 = TestUtilities.getArticleAsADraft('New title', 'new-url-fake-name' + Crypto.getRandomInteger());
        newArticle1.Division__c = 'Financial Management';
        newArticle1.Product__c = 'Dimensions';
        newArticle1.Product_Features__c = 'ADM';

        insert newArticle1;
        String articleId1 = [SELECT KnowledgeArticleId FROM Knowledge__kav WHERE Id =: newArticle1.Id].KnowledgeArticleId;
        KbManagement.PublishingService.publishArticle(articleId1, true);

        Map<String, Object> knowledgeResult1 = CspKnowledge.getKnowledgeArticle(newArticle1.UrlName);

        System.assert(knowledgeResult1 != null);
        System.assert(knowledgeResult1.get('Title') == newArticle1.Title);
        System.assert(knowledgeResult1.get('ProductName') == null);

    }
}