force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Information__c</fullName>
    <description>e.g. information about add-ons/any system requirements/other software the upgrade might affect etc (could also link off to other articles if needed)</description>
    <inlineHelpText>e.g. information about add-ons/any system requirements/other software the upgrade might affect etc (could also link off to other articles if needed)</inlineHelpText>
    <label>Additional information</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Article_Header_Image_Formula__c.field-meta.xml
<CustomField>
    <fullName>Article_Header_Image_Formula__c</fullName>
    <description>Formula to set the URL on an article header</description>
    <formula>Knowledge_Edition_Image__r.Image_URL__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Article Header Image Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Enviroment__c.field-meta.xml
<CustomField>
    <fullName>Enviroment__c</fullName>
    <label>Environment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/How_this_version_will_be_made_available__c.field-meta.xml
<CustomField>
    <fullName>How_this_version_will_be_made_available__c</fullName>
    <label>How this version will be made available</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Information_Article_Body__c.field-meta.xml
<CustomField>
    <fullName>Information_Article_Body__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Join_the_converstaion__c.field-meta.xml
<CustomField>
    <fullName>Join_the_converstaion__c</fullName>
    <description>generic footer to post any questions, feedback, etc in a new community post we’ll create for the release</description>
    <inlineHelpText>generic footer to post any questions, feedback, etc in a new community post we’ll create for the release</inlineHelpText>
    <label>Join the conversation</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Division__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Release_note_image__c.field-meta.xml
<CustomField>
    <fullName>Release_note_image__c</fullName>
    <description>A product-specific image used to distinguish between sets of release notes.</description>
    <label>Release note image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <label>Solution</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/What_s_New__c.field-meta.xml
<CustomField>
    <fullName>What_s_New__c</fullName>
    <description>summary of each feature with a link to an article if a more detailed one is required</description>
    <inlineHelpText>summary of each feature with a link to an article if a more detailed one is required</inlineHelpText>
    <label>What&apos;s new</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/ProductRouting__c/ProductRouting__c.object-meta.xml
<CustomObject>
    <label>Product Routing</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Routings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductRouting__c/fields/ImageUrl__c.field-meta.xml
<CustomField>
    <fullName>ImageUrl__c</fullName>
    <description>Field to configure the product logo image, via a url linking to the relevant asset file.</description>
    <inlineHelpText>Enter a relative url linking to the content asset file which contains the logo for this product routing</inlineHelpText>
    <label>Image Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/ProductColour__c.field-meta.xml
<CustomField>
    <fullName>ProductColour__c</fullName>
    <description>The Colour which represents this product in the success community portal</description>
    <inlineHelpText>Select a product colour to represent this product in the success community portal</inlineHelpText>
    <label>Product Colour</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Colour 1</fullName>
            </value>
            <value>
                <fullName>Colour 2</fullName>
            </value>
            <value>
                <fullName>Colour 3</fullName>
            </value>
            <value>
                <fullName>Colour 4</fullName>
            </value>
            <value>
                <fullName>Colour 5</fullName>
            </value>
            <value>
                <fullName>Colour 6</fullName>
            </value>
            <value>
                <fullName>Colour 7</fullName>
            </value>
            <value>
                <fullName>Colour 8</fullName>
            </value>
            <value>
                <fullName>Colour 9</fullName>
            </value>
            <value>
                <fullName>Colour 10</fullName>
            </value>
            <value>
                <fullName>Colour 11</fullName>
            </value>
            <value>
                <fullName>Colour 12</fullName>
            </value>
            <value>
                <fullName>Colour 13</fullName>
            </value>
            <value>
                <fullName>Colour 14</fullName>
            </value>
            <value>
                <fullName>Colour 15</fullName>
            </value>
            <value>
                <fullName>Colour 16</fullName>
            </value>
            <value>
                <fullName>Colour 17</fullName>
            </value>
            <value>
                <fullName>Colour 18</fullName>
            </value>
            <value>
                <fullName>Colour 19</fullName>
            </value>
            <value>
                <fullName>Colour 20</fullName>
            </value>
            <value>
                <fullName>Colour 21</fullName>
            </value>
            <value>
                <fullName>Colour 22</fullName>
            </value>
            <value>
                <fullName>Colour 23</fullName>
            </value>
            <value>
                <fullName>Colour 24</fullName>
            </value>
            <value>
                <fullName>Colour 25</fullName>
            </value>
            <value>
                <fullName>Colour 26</fullName>
            </value>
            <value>
                <fullName>Colour 27</fullName>
            </value>
            <value>
                <fullName>Colour 28</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/Related_Product_Range__c.field-meta.xml
<CustomField>
    <fullName>Related_Product_Range__c</fullName>
    <label>Related Product Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CspKnowledge.cls
public with sharing class CspKnowledge {
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getKnowledgeArticle(String urlName){

        Knowledge__kav article = [
            SELECT Information_Article_Body__c, Product__c,
                Product_Features__c, Solution__c, Title, UrlName,
                LastPublishedDate, ArticleTotalViewCount, Enviroment__c,
                RecordType.DeveloperName, Release_note_image__c, What_s_New__c,
                How_this_version_will_be_made_available__c,
                Additional_Information__c, Join_the_converstaion__c, Article_Header_Image_Formula__c
            FROM Knowledge__kav
            WHERE UrlName =: urlName
            AND PublishStatus = 'Online'
            UPDATE VIEWSTAT
        ];

        try {
            ProductRouting__c pr = [
                SELECT Id, ProductColour__c, ImageUrl__c
                FROM ProductRouting__c
                WHERE Related_Product_Range__c =: article.Product__c
                LIMIT 1
            ];

            return new Map<String, Object>{
                'Id' => article.Id,
                'Url' => article.UrlName,
                'Title' => article.Title,
                'Views' => article.ArticleTotalViewCount,
                'Solution' => article.Solution__c,
                'Description' => article.Information_Article_Body__c,
                'Environment' => article.Enviroment__c,
                'PublishedDate' => article.LastPublishedDate,
                'ProductName' => article.Product__c,
                'ProductFeatures' => article.Product_Features__c,
                'RecordType' => article.RecordType.DeveloperName,
                'RelaseNoteImage' => article.Release_note_image__c,
                'WhatsNew' => article.What_s_New__c,
                'HowAvailable' => article.How_this_version_will_be_made_available__c,
                'AdditionalInformation' => article.Additional_Information__c,
                'JoinConversation' => article.Join_the_converstaion__c,
                'ArticleHeaderImage' => article.Article_Header_Image_Formula__c,
                'ProductColour' => pr.ProductColour__c != null ? pr.ProductColour__c.replace('Colour ', '') : '',
                'ProductImage' => pr.ImageUrl__c,
                'ProductId' => pr.Id
            };

        } catch(QueryException e) {
            return new Map<String, Object>{
                'Id' => article.Id,
                'Url' => article.UrlName,
                'Title' => article.Title,
                'Views' => article.ArticleTotalViewCount,
                'Solution' => article.Solution__c,
                'Description' => article.Information_Article_Body__c,
                'Environment' => article.Enviroment__c,
                'PublishedDate' => article.LastPublishedDate,
                'RecordType' => article.RecordType.DeveloperName,
                'RelaseNoteImage' => article.Release_note_image__c,
                'WhatsNew' => article.What_s_New__c,
                'HowAvailable' => article.How_this_version_will_be_made_available__c,
                'AdditionalInformation' => article.Additional_Information__c,
                'JoinConversation' => article.Join_the_converstaion__c,
                'ArticleHeaderImage' => article.Article_Header_Image_Formula__c
            };
        }
    }
}