force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Modules</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Modules</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Asset_Family__c.field-meta.xml
<CustomField>
    <fullName>Asset_Family__c</fullName>
    <label>Asset Family</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>aCloud</fullName>
            </value>
            <value>
                <fullName>Delta</fullName>
            </value>
            <value>
                <fullName>Dimensions</fullName>
            </value>
            <value>
                <fullName>FocalPoint</fullName>
            </value>
            <value>
                <fullName>Goldmine</fullName>
            </value>
            <value>
                <fullName>Orchestrate</fullName>
            </value>
            <value>
                <fullName>Payroll</fullName>
            </value>
            <value>
                <fullName>PeoplePlanner</fullName>
            </value>
            <value>
                <fullName>Supply Chain</fullName>
            </value>
            <value>
                <fullName>Hosting HCM</fullName>
            </value>
            <value>
                <fullName>Hosting NFP</fullName>
            </value>
            <value>
                <fullName>Hosting FMS</fullName>
            </value>
            <value>
                <fullName>Hosting SCS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module__c/fields/Asset_Status__c.field-meta.xml
<CustomField>
    <fullName>Asset_Status__c</fullName>
    <label>Asset Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Purchased</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Installed</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Obsolete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Standard</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Modules</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Contract_Status__c.field-meta.xml
<CustomField>
    <fullName>Contract_Status__c</fullName>
    <label>Contract Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Contract_Version__c.field-meta.xml
<CustomField>
    <fullName>Contract_Version__c</fullName>
    <label>Contract Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/DNR_Date__c.field-meta.xml
<CustomField>
    <fullName>DNR_Date__c</fullName>
    <label>DNR Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/DNR_Reason_Code_1__c.field-meta.xml
<CustomField>
    <fullName>DNR_Reason_Code_1__c</fullName>
    <label>DNR Reason Code 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/DNR_Reason_Code_2__c.field-meta.xml
<CustomField>
    <fullName>DNR_Reason_Code_2__c</fullName>
    <label>DNR Reason Code 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Do_Not_Renew__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Renew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do Not Renew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Expected_Warranty_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Warranty_End_Date__c</fullName>
    <label>Expected Warranty End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Install_Date__c.field-meta.xml
<CustomField>
    <fullName>Install_Date__c</fullName>
    <label>Install Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Integration_Id__c.field-meta.xml
<CustomField>
    <fullName>Integration_Id__c</fullName>
    <label>Integration Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/License_Key__c.field-meta.xml
<CustomField>
    <fullName>License_Key__c</fullName>
    <label>License Key</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Number_of_Users__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Users__c</fullName>
    <label>Number of Users</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Modules</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Original_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Original_Start_Date__c</fullName>
    <label>Original Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Product_Code_SME__c.field-meta.xml
<CustomField>
    <fullName>Product_Code_SME__c</fullName>
    <label>Product Code (SME)</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Product_Name_SME__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_SME__c</fullName>
    <label>Product Name (SME)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Product_SKU__c.field-meta.xml
<CustomField>
    <fullName>Product_SKU__c</fullName>
    <label>Product SKU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Renewal_Price__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Price__c</fullName>
    <label>Renewal Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Revenue_Type__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Type__c</fullName>
    <label>Revenue Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Licences</fullName>
            </value>
            <value>
                <fullName>Annual Licences</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>SAAS</fullName>
            </value>
            <value>
                <fullName>Subscriptions</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <label>Serial Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Total_Renewal_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Renewal_Price__c</fullName>
    <label>Total Renewal Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Usage_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Usage_End_Date__c</fullName>
    <label>Usage End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AssetTriggerHandler.cls
public with sharing class AssetTriggerHandler {
    public static Boolean disableAssetTrigger = false;
    public static Boolean disableBaseElementDeactivatation = false;
    public static Boolean disableBaseElementActivatation = false;

    @TestVisible
    private Map<Id, Asset> newAssetsMap {
        get {
            if (newAssetsMap == null) {
                newAssetsMap = new Map<Id, Asset>();
            }

            return newAssetsMap;
        }
        set;
    }

    @TestVisible
    private Map<Id, Asset> oldAssetsMap {
        get {
            if (oldAssetsMap == null) {
                oldAssetsMap = new Map<Id, Asset>();
            }

            return oldAssetsMap;
        }
        set;
    }

    @TestVisible
    private AssetTriggerHandler() { }

    public static AssetTriggerHandler getInstance(Map<Id, Asset> newAssetsMap, Map<Id, Asset> oldAssetsMap) {
        AssetTriggerHandler handler = new AssetTriggerHandler();
        handler.newAssetsMap = newAssetsMap;
        handler.oldAssetsMap = oldAssetsMap;

        return handler;
    }

    public static void createModules(Map<Id, Asset> assets) {
        List<Id> assetContractIds = new List<Id>();
        for(Asset asset: assets.values()) {
            assetContractIds.add(asset.Contract__c);
        }
        
        // Used later to determine if contracts for the assets are 
        // valid according to criteria - active and with an end date
        Map<Id, Contract> contractMap = new Map<Id, Contract>([
            SELECT Id,
                AccountId, 
                Account.Name,
                Account.OwnerId,
                Name, 
                Contract_Status__c, 
                CustomerSignedId, 
                EndDate, 
                Contract_End_Date__c,
                Last_Uplift_Date__c,
                Price_Before_Last_Uplift__c,
                IsDealer__c,
                Do_Not_Renew__c
            FROM Contract 
            WHERE Id IN: assetContractIds
        ]);
        
        // Find an existing opportunitity for the contracts 
        // associated with these assets, key with contract ID
        List<Opportunity> opportunities = [
            SELECT Id, ContractId 
            FROM Opportunity 
            WHERE ContractId IN: assetContractIds
            AND RecordType.Name =: ContractTriggerHandler.RENEWAL_RECORD_TYPE
        ];
        Map<Id, Opportunity> opportunityMap = new Map<Id, Opportunity>();
        for(Opportunity opportunity: opportunities) {
            opportunityMap.put(opportunity.ContractId, opportunity);
        }

        List<Module__c> modulesToCreate = new List<Module__c>();
        Map<Id, Asset> modulesToCreateAfterOpportunity = new Map<Id, Asset>();
        List<Id> opportunitiesToCreate = new List<Id>();
        for (Asset asset: assets.values()) {
            try {
                // If contract associated with these assets doesn't meet criteria
                // then do not create modules or opportunity
                Contract contract = contractMap.get(asset.Contract__c);
                if(contract.Contract_Status__c != 'Active' || contract.EndDate == null) {
                    continue;
                }
            } catch(Exception e) {
                continue;
            }
            
            try {
                Opportunity opportunity = opportunityMap.get(asset.Contract__c);
                modulesToCreate.add(AssetTriggerHandler.mapAssetToModule(asset, opportunity.Id));            
            } catch(Exception e) {
                opportunitiesToCreate.add(asset.Contract__c);
                modulesToCreateAfterOpportunity.put(asset.Id, asset);
            }
        }   
        insert modulesToCreate;
        
        // Any assets that were due to have modules created but couldn't
        // due to missing opportunity are created here and ran again
        if(opportunitiesToCreate.size() > 0) {
            Map<Id, Contract> contracts = new Map<Id, Contract>([
                SELECT Id, 
                    AccountId, 
                    Account.Name,
                    Account.OwnerId,
                    Name, 
                    Contract_Status__c, 
                    CustomerSignedId, 
                    EndDate, 
                    Contract_End_Date__c,
                    Last_Uplift_Date__c,
                    Price_Before_Last_Uplift__c,
                    IsDealer__c,
                    Do_Not_Renew__c
                FROM Contract
                WHERE Id IN: opportunitiesToCreate
            ]);
            
            for(Contract contract: contracts.values()) {
                ContractTriggerHandler.createRenewalOpportunity(contracts);
            }
            
            AssetTriggerHandler.createModules(modulesToCreateAfterOpportunity);
        }
    }
    
    public static void updateModules(Map<Id, Asset> assets) {
        // Find any existing modules for the assets in the list
        // and key them with the asset ID
        List<Module__c> modules = [
            SELECT Id, Asset__c, Contract__c, Account__c
            FROM Module__c
            WHERE Asset__c IN: assets.keySet()
        ]; 
        Map<Id, Module__c> modulesByAssetId = new Map<Id, Module__c>();
        for(Module__c module: modules) {
            modulesByAssetId.put(module.Asset__c, module);
        }
                
        List<Module__c> modulesToUpdate = new List<Module__c>();
        Map<Id, Asset> modulesToCreate = new Map<Id, Asset>();
        for (Asset asset: assets.values()) {
            // Map the Asset to the Module and update it, if the Module can't 
            // be found then add it to a list to be created 
            Module__c module = AssetTriggerHandler.mapAssetToModule(asset, null);  
            try {
                module.Id = modulesByAssetId.get(asset.Id).Id;
                modulesToUpdate.add(module);
            } catch(Exception e) {
                modulesToCreate.put(asset.Id, asset);
            }
        }
        update modulesToUpdate;
        
        // No existing module for this asset
        if(modulesToCreate.size() > 0) {
            AssetTriggerHandler.createModules(modulesToCreate);
        }
    }

    public static Module__c mapAssetToModule(Asset asset, Id opportunityId) {
        return new Module__c(
            Account__c = asset.AccountId,
            CurrencyIsoCode = asset.CurrencyIsoCode,
            Asset_Family__c = asset.Asset_Family__c,
            Name = asset.Name,
            Asset_Status__c = asset.Status,
            Contract__c = asset.Contract__c,
            Contract_End_Date__c = asset.Contract_End_Date__c,
            Contract_Status__c = asset.Contract_Status__c,
            Contract_Version__c = asset.Contract_Version__c,
            Description__c = asset.Description,
            DNR_Date__c = asset.DNR_Date__c,
            DNR_Reason_Code_1__c = asset.DNR_Reason_Code_1__c,
            DNR_Reason_Code_2__c = asset.DNR_Reason_Code_2__c,
            Do_Not_Renew__c = asset.Do_Not_Renew__c,
            Expected_Warranty_End_Date__c = asset.Expected_Warranty_End_Date__c,
            Install_Date__c = asset.InstallDate,
            Integration_Id__c = asset.Integration_Id__c,
            License_Key__c = asset.LicenseKey__c,
            Module__c = asset.Module__c,
            Number_of_Users__c = asset.Number_of_Users__c,
            Opportunity__c = opportunityId,
            Original_Start_Date__c = asset.Original_Start_Date__c,
            Price__c = asset.Price,
            Product__c = asset.Product2Id,
            Product_Code_SME__c = asset.Product_Code_SME__c,
            Product_Name_SME__c = asset.Product_Name_SME__c,
            Product_Code__c = asset.ProductCode,
            Product_SKU__c = asset.StockKeepingUnit,
            Quantity__c = asset.Quantity,
            Renewal_Price__c = asset.Renewal_Price__c,
            Revenue_Type__c = asset.ProductFamily,
            Serial_Number__c = asset.SerialNumber,
            Total_Price__c = asset.Total_Price__c,
            Total_Renewal_Price__c = asset.Total_Renewal_Price__c,
            Usage_End_Date__c = asset.UsageEndDate,
            Asset__c = asset.Id
        );
    }

    private class AssetTriggerException extends Exception { }
}