force-app/main/default/objects/ContactEntitlement__c/ContactEntitlement__c.object-meta.xml
<CustomObject>
    <label>Contact Entitlement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Entitlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactEntitlement__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF(Real_Entitlement__r.EndDate &lt; TODAY(),false,true)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ContactEntitlement__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>ContactEntitlements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactEntitlement__c/fields/ContactID18__c.field-meta.xml
<CustomField>
    <fullName>ContactID18__c</fullName>
    <formula>CASESAFEID(  Contact__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ContactID18</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactEntitlement__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>TEXT(Real_Entitlement__r.AssociatedProductRange__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactEntitlement__c/fields/Real_Entitlement__c.field-meta.xml
<CustomField>
    <fullName>Real_Entitlement__c</fullName>
    <label>Entitlement Real</label>
    <referenceTo>Entitlement</referenceTo>
    <relationshipLabel>Contact Entitlements</relationshipLabel>
    <relationshipName>Contact_Entitlements</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactEntitlement__c/fields/Topic_ID__c.field-meta.xml
<CustomField>
    <fullName>Topic_ID__c</fullName>
    <formula>Real_Entitlement__r.TopicID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Topic ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductRouting__c/ProductRouting__c.object-meta.xml
<CustomObject>
    <label>Product Routing</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Routings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductRouting__c/fields/Community_Redirect__c.field-meta.xml
<CustomField>
    <fullName>Community_Redirect__c</fullName>
    <label>Community Redirect</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/Dedicated_Telephone_Number__c.field-meta.xml
<CustomField>
    <fullName>Dedicated_Telephone_Number__c</fullName>
    <label>Dedicated Telephone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/Enabled_For_Community__c.field-meta.xml
<CustomField>
    <fullName>Enabled_For_Community__c</fullName>
    <label>Enabled For Community</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Redirection</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/Enabled_for_FlexPoints__c.field-meta.xml
<CustomField>
    <fullName>Enabled_for_FlexPoints__c</fullName>
    <label>Enabled for FlexPoints</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/Enabled_For_Live_Chat__c.field-meta.xml
<CustomField>
    <fullName>Enabled_For_Live_Chat__c</fullName>
    <label>Enabled For Live Chat</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/Enabled_For_Telephony__c.field-meta.xml
<CustomField>
    <fullName>Enabled_For_Telephony__c</fullName>
    <label>Enabled For Telephony</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/Enabled_For_Web_Cases__c.field-meta.xml
<CustomField>
    <fullName>Enabled_For_Web_Cases__c</fullName>
    <label>Enabled For Web Cases</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/ImageUrl__c.field-meta.xml
<CustomField>
    <fullName>ImageUrl__c</fullName>
    <description>Field to configure the product logo image, via a url linking to the relevant asset file.</description>
    <inlineHelpText>Enter a relative url linking to the content asset file which contains the logo for this product routing</inlineHelpText>
    <label>Image Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/Live_Chat_Button_ID__c.field-meta.xml
<CustomField>
    <fullName>Live_Chat_Button_ID__c</fullName>
    <label>Live Chat Button ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/Livechat_Levels__c.field-meta.xml
<CustomField>
    <fullName>Livechat_Levels__c</fullName>
    <label>Live Chat Plan Availability</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Classic</fullName>
            </value>
            <value>
                <fullName>Essential</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Premier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/Phone_Plan_Availability__c.field-meta.xml
<CustomField>
    <fullName>Phone_Plan_Availability__c</fullName>
    <description>Limits phone availability based on success plan</description>
    <label>Phone Plan Availability</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Classic</fullName>
            </value>
            <value>
                <fullName>Essential</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Premier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/ProductColour__c.field-meta.xml
<CustomField>
    <fullName>ProductColour__c</fullName>
    <description>The Colour which represents this product in the success community portal</description>
    <inlineHelpText>Select a product colour to represent this product in the success community portal</inlineHelpText>
    <label>Product Colour</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Colour 1</fullName>
            </value>
            <value>
                <fullName>Colour 2</fullName>
            </value>
            <value>
                <fullName>Colour 3</fullName>
            </value>
            <value>
                <fullName>Colour 4</fullName>
            </value>
            <value>
                <fullName>Colour 5</fullName>
            </value>
            <value>
                <fullName>Colour 6</fullName>
            </value>
            <value>
                <fullName>Colour 7</fullName>
            </value>
            <value>
                <fullName>Colour 8</fullName>
            </value>
            <value>
                <fullName>Colour 9</fullName>
            </value>
            <value>
                <fullName>Colour 10</fullName>
            </value>
            <value>
                <fullName>Colour 11</fullName>
            </value>
            <value>
                <fullName>Colour 12</fullName>
            </value>
            <value>
                <fullName>Colour 13</fullName>
            </value>
            <value>
                <fullName>Colour 14</fullName>
            </value>
            <value>
                <fullName>Colour 15</fullName>
            </value>
            <value>
                <fullName>Colour 16</fullName>
            </value>
            <value>
                <fullName>Colour 17</fullName>
            </value>
            <value>
                <fullName>Colour 18</fullName>
            </value>
            <value>
                <fullName>Colour 19</fullName>
            </value>
            <value>
                <fullName>Colour 20</fullName>
            </value>
            <value>
                <fullName>Colour 21</fullName>
            </value>
            <value>
                <fullName>Colour 22</fullName>
            </value>
            <value>
                <fullName>Colour 23</fullName>
            </value>
            <value>
                <fullName>Colour 24</fullName>
            </value>
            <value>
                <fullName>Colour 25</fullName>
            </value>
            <value>
                <fullName>Colour 26</fullName>
            </value>
            <value>
                <fullName>Colour 27</fullName>
            </value>
            <value>
                <fullName>Colour 28</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/Related_Product_Range__c.field-meta.xml
<CustomField>
    <fullName>Related_Product_Range__c</fullName>
    <label>Related Product Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/TopicID__c.field-meta.xml
<CustomField>
    <fullName>TopicID__c</fullName>
    <description>Used by the community</description>
    <label>Topic ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/Visibility__c.field-meta.xml
<CustomField>
    <fullName>Visibility__c</fullName>
    <defaultValue>(&quot;Public&quot;)</defaultValue>
    <description>Visibility of community articles related to this product</description>
    <inlineHelpText>Select &apos;Public&apos; to show content to all users, &apos;Admin&apos; to limit visibility to community admin users and &apos;None&apos; to hide</inlineHelpText>
    <label>Visibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Public</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/cspProductSelection.cls
public without sharing class cspProductSelection {
    @AuraEnabled(cacheable=true)
    public static List<Map<String, String>> getAllProducts(String selectedAccId) {
        return cspProductSelection.getFullProductList(true, selectedAccId);
    }

    @AuraEnabled(cacheable=true)
    public static List<Map<String, String>> getProductList() {
        return cspProductSelection.getFullProductList(false, '');
    }

    @AuraEnabled(cacheable=true)
    public static List<Map<String, String>> getProductList(String selectedAccId) {
        return cspProductSelection.getFullProductList(false, selectedAccId);
    }

    private static List<Map<String, String>> getFullProductList(Boolean allProducts, String selectedAccId) {
        List<Map<String, String>> productList = cspProductSelection.getProductRoutingProducts();
        System.debug('*** selectedAccId: ' + selectedAccId);
        Boolean bypassEntitlements = FeatureManagement.checkPermission('Bypass_Entitlements_Check');
        System.debug('*** bypassEntitlements: ' + bypassEntitlements);
        if (bypassEntitlements) {
            // The current profile can see all products with no entitlement requirements
            for (Map<String,String> product : productList) {
                product.put('successPlanName', 'Internal');
                product.put('successPlan', 'Internal Staff Access');
                product.put('admin', 'true');
            }
        }
        if (bypassEntitlements || allProducts) {
            System.debug('*** productList: ' + productList);

            return productList;
        }

        List<Entitlement> accountEntitlements = cspProductSelection.getAccountEntitlements(selectedAccId);
        List<ContactEntitlement__c> contactEntitlements = cspProductSelection.getMyEntitlements(selectedAccId);
        if (accountEntitlements.size() > 0) {
            List<Map<String, String>> entitledProducts = new List<Map<String, String>>();
            for (Map<String,String> product : productList) {
                for (Entitlement accountEnt : accountEntitlements) {
                    if (product.get('name').equals(accountEnt.AssociatedProductRange__c)) {
                        product.put('entitlementId', accountEnt.Id);
                        product.put('successPlanName', accountEnt.PlanType__c);
                        product.put('successPlan', accountEnt.PlanType__c + ' Success Plan');
                        for (ContactEntitlement__c entitlement : contactEntitlements) {
                            if (product.get('name').equals(entitlement.Product__c)) {
                                product.put('admin', 'true');
                                break;
                            }
                        }
                        entitledProducts.add(product);
                        break;
                    }
                }
            }
            return entitledProducts;
        } else {
            // If the user has no entitlements, return no products
            return new List<Map<String, String>>();
        }
    }

    public static List<String> getFlatProductList(String selectedAccId) {
        List<Map<String, String>> productList = cspProductSelection.getProductList(selectedAccId);

        List<String> flatProductList = new List<String>();

        for (Map<String,String> product : productList) {
            flatProductList.add(product.get('name'));
        }
        return flatProductList;
    }

    public static List<String> getEntitledProductList(String selectedAccId) {
        List<Map<String, String>> productList = cspProductSelection.getProductList(selectedAccId);

        List<String> flatProductList = new List<String>();

        for (Map<String,String> product : productList) {
            if (product.get('admin') != null && product.get('admin').equals('true')) {
                flatProductList.add(product.get('name'));
            }
        }
        return flatProductList;
    }

    @AuraEnabled
    public static Map<String, String> getProduct(String productName, String selectedAccId) {
        List<Map<String, String>> productList = cspProductSelection.getProductList(selectedAccId);

        for (Map<String, String> product : productList) {
            if (product.get('name').equals(productName)) {
                return product;
            }
        }
        return null;
    }

    @AuraEnabled
    public static List<ContactEntitlement__c> getMyEntitlements(String selectedAccId) {
        string contactiduser = [Select contactid from User where id = :Userinfo.getUserid()].contactId;
        List<ContactEntitlement__c> objList = new List<ContactEntitlement__c>();
        for (ContactEntitlement__c entitlement : [
            SELECT Product__C, Topic_ID__c, Real_Entitlement__r.PlanType__c
            FROM ContactEntitlement__c
            WHERE Active__C = true
            AND Real_Entitlement__r.AccountId =:selectedAccId
            AND (Contact__C = :contactiduser or ContactID18__C =:contactiduser)
            order by Real_Entitlement__r.Entitlement_Level__c
        ]) {
                objList.add(entitlement);
        }
        return objList;
    }

    @AuraEnabled
    public static List<ContactEntitlement__c> getContactEntitlements(String selectedAccId, String contactId) {
        List<ContactEntitlement__c> objList = new List<ContactEntitlement__c>();
        for (ContactEntitlement__c entitlement : [
            SELECT Product__C, Topic_ID__c, Real_Entitlement__r.PlanType__c
            FROM ContactEntitlement__c
            WHERE Active__C = true
            AND Real_Entitlement__r.AccountId =:selectedAccId
            AND (Contact__C = :contactId or ContactID18__C =:contactId)
        ]) {
                objList.add(entitlement);
        }
        return objList;
    }

    @AuraEnabled
    public static List<Entitlement> getAccountEntitlements(String selectedAccId) {
        string contactiduser = [Select contactid from User where id = :Userinfo.getUserid()].contactId;
        List<Entitlement> objList = new List<Entitlement>();
        if (selectedAccId != null) {
            for (Entitlement entitlement : [
                SELECT Id, AssociatedProductRange__c, PlanType__c
                FROM Entitlement
                WHERE Active__c = true
                AND AccountId = :selectedAccId
                order by Entitlement_Level__c
            ]) {
                    objList.add(entitlement);
            }
        } else {
            String customerSuccessRole = 'Customer Success Portal Access';
            List<AccountContactRelation> accountContactRelations = [
                SELECT Account.Id FROM AccountContactRelation
                WHERE Contact.Id =: contactiduser
                AND (Roles INCLUDES (:customerSuccessRole) OR IsDirect = true)
            ];

            List<String> accountIds = new List<String>();
            for (AccountContactRelation accountContactRelation : accountContactRelations) {
                accountIds.add(accountContactRelation.Account.Id);
            }
            for (Entitlement entitlement : [
                SELECT Id, AssociatedProductRange__c, PlanType__c
                FROM Entitlement
                WHERE Active__c = true
                AND AccountId IN :accountIds
            ]) {
                    objList.add(entitlement);
            }
        }
        return objList;
    }

    @AuraEnabled
    public static List<Map<String, String>> getProductRoutingProducts() {
        List<Map<String, String>> productRoutingList = new List<Map<String, String>>();

        for(ProductRouting__c productRouting: [
            SELECT Id, Related_Product_Range__c, ImageUrl__c, ProductColour__c,
                Enabled_For_Live_Chat__c, Enabled_For_Telephony__c, Enabled_for_FlexPoints__c,
                Enabled_For_Web_Cases__c, Dedicated_Telephone_Number__c,
                Live_Chat_Button_ID__c, TopicID__c, Community_Redirect__c, Enabled_For_Community__c, Livechat_Levels__c, Phone_Plan_Availability__c
            FROM ProductRouting__c
            WHERE Related_Product_Range__c != null
            AND Visibility__c = 'Public'
            ORDER BY Related_Product_Range__c
        ]) {
            String productId = productRouting.Id;
            String productName = productRouting.Related_Product_Range__c;
            String imageUrl = productRouting.ImageUrl__c;
            String productColour = productRouting.ProductColour__c;
            String chatEnabled = productRouting.Enabled_For_Live_Chat__c;
            String phoneEnabled = productRouting.Enabled_For_Telephony__c;
            String onlineEnabled = productRouting.Enabled_For_Web_Cases__c;
            String phoneNumber = productRouting.Dedicated_Telephone_Number__c;
            String liveChatButton = productRouting.Live_Chat_Button_ID__c;
            String topicId = productRouting.TopicID__c;
            String communityRedirect = productRouting.Community_Redirect__c;
            String enabledForCommunity = productRouting.Enabled_For_Community__c;
            String livechatlevel = productRouting.Livechat_Levels__c;
            String PhonePlanAvaliblity = productRouting.Phone_Plan_Availability__c;
            String flexPointsEnabled = productRouting.Enabled_for_FlexPoints__c;
            Map<String, String> productMap = new Map<String, String>{
                'colour' => productColour != null ? productColour.replace('Colour ', '') : '',
                'id' => productId,
                'image' => imageUrl,
                'name' => productName,
                'enabledForChat' => chatEnabled,
                'enabledForPhone' => phoneEnabled,
                'enabledForOnline' => onlineEnabled,
                'phoneNumber' => phoneNumber,
                'liveChatButton' => liveChatButton,
                'topicId' => topicId,
                'communityRedirect' => communityRedirect,
                'enabledForCommunity' => enabledForCommunity,
                'livechatlevel' => livechatlevel,
                'PhonePlanAvalibility' => PhonePlanAvaliblity,
                'flexPointsEnabled' => flexPointsEnabled
            };
            productRoutingList.add(productMap);
        }
        return productRoutingList;
    }
}