force-app/main/default/objects/ContactEntitlement__c/ContactEntitlement__c.object-meta.xml
<CustomObject>
    <label>Contact Entitlement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Entitlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactEntitlement__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>ContactEntitlements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactEntitlement__c/fields/Real_Entitlement__c.field-meta.xml
<CustomField>
    <fullName>Real_Entitlement__c</fullName>
    <label>Entitlement Real</label>
    <referenceTo>Entitlement</referenceTo>
    <relationshipLabel>Contact Entitlements</relationshipLabel>
    <relationshipName>Contact_Entitlements</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProductRouting__c/ProductRouting__c.object-meta.xml
<CustomObject>
    <label>Product Routing</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Routings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductRouting__c/fields/Product_Division__c.field-meta.xml
<CustomField>
    <fullName>Product_Division__c</fullName>
    <label>Product Division</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Division</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/Related_Product_Range__c.field-meta.xml
<CustomField>
    <fullName>Related_Product_Range__c</fullName>
    <label>Related Product Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductRouting__c/fields/Visibility__c.field-meta.xml
<CustomField>
    <fullName>Visibility__c</fullName>
    <defaultValue>(&quot;Public&quot;)</defaultValue>
    <description>Visibility of community articles related to this product</description>
    <inlineHelpText>Select &apos;Public&apos; to show content to all users, &apos;Admin&apos; to limit visibility to community admin users and &apos;None&apos; to hide</inlineHelpText>
    <label>Visibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Public</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/Service_Catalogues__c.object-meta.xml
<CustomObject>
    <label>Services Catalogue</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Service Catalogue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services Catalogue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Catalogues__c/fields/Account_Journey_Stage__c.field-meta.xml
<CustomField>
    <fullName>Account_Journey_Stage__c</fullName>
    <label>Account Journey Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New to Product</fullName>
            </value>
            <value>
                <fullName>In first year of using product</fullName>
            </value>
            <value>
                <fullName>Been using the product for some time</fullName>
            </value>
            <value>
                <fullName>Applicable to all</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Delivered_By__c.field-meta.xml
<CustomField>
    <fullName>Delivered_By__c</fullName>
    <label>Delivered By</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Customer Success Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <label>Delivery Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bite Size</fullName>
            </value>
            <value>
                <fullName>Virtual Classroom</fullName>
            </value>
            <value>
                <fullName>Classroom</fullName>
            </value>
            <value>
                <fullName>1:1 Consulting</fullName>
            </value>
            <value>
                <fullName>1:Many Consulting</fullName>
            </value>
            <value>
                <fullName>Remote Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Remote</fullName>
            </value>
            <value>
                <fullName>Onsite</fullName>
            </value>
            <value>
                <fullName>Access Office Location</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Points_Conversion__c.field-meta.xml
<CustomField>
    <fullName>Points_Conversion__c</fullName>
    <label>Points Conversion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <label>Products</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Community_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Service_Description__c.field-meta.xml
<CustomField>
    <fullName>Service_Description__c</fullName>
    <label>Service Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Service_Title__c.field-meta.xml
<CustomField>
    <fullName>Service_Title__c</fullName>
    <label>Service Title</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Analytics/Reporting</fullName>
            </value>
            <value>
                <fullName>Configurations and Customisation</fullName>
            </value>
            <value>
                <fullName>Education/Training</fullName>
            </value>
            <value>
                <fullName>Flightpath Implementation Extras/Add Ons</fullName>
            </value>
            <value>
                <fullName>Integrations</fullName>
            </value>
            <value>
                <fullName>Strategic Engagements</fullName>
            </value>
            <value>
                <fullName>Upgrade and Migration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/User_Level__c.field-meta.xml
<CustomField>
    <fullName>User_Level__c</fullName>
    <label>User Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beginner</fullName>
            </value>
            <value>
                <fullName>Competent</fullName>
            </value>
            <value>
                <fullName>Expert</fullName>
            </value>
            <value>
                <fullName>Available for all levels</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/cspServiceCatalogueEntryHandlerTest.cls
@isTest
public with sharing class cspServiceCatalogueEntryHandlerTest {
    @isTest
    public static void getServiceCatalogueEntry() {

        User portalAccountOwner1 = TestUtilities.createUser('Support Admin', 'System Administrator', 'test123');

        System.runAs(portalAccountOwner1) {
            // Create account
    		Account portalAccount1 = new Account(Name = 'TestAccount', OwnerId = portalAccountOwner1.Id);
    		insert portalAccount1;

            //Create contact
			Contact contact1 = new Contact(FirstName = 'Test', 
            Lastname = 'McTesty', 
            AccountId = portalAccount1.Id, 
            Email = System.now().millisecond() + 'test@test.com');

            insert contact1;
            //Create our portal user
            User user1 = TestUtilities.createPortalUser('Customer Portal - Support User', contact1.Id, 'test123p');

        }
        Account a = [SELECT Id FROM Account WHERE Name = 'TestAccount'];
        User u = [SELECT Id, email, ContactId FROM User WHERE alias = 'test123' LIMIT 1];
        System.runAs(u) {
            Service_Catalogues__c serviceCatalogueEntry = new Service_Catalogues__c();
            serviceCatalogueEntry.Service_Description__c = 'Entry Description';
            serviceCatalogueEntry.Points_Conversion__c = 10000;
            serviceCatalogueEntry.Service_Title__c = 'Catalogue Entry';
            serviceCatalogueEntry.Account_Journey_Stage__c = 'Applicable to all';
            serviceCatalogueEntry.Delivered_By__c = 'Professional Services';
            serviceCatalogueEntry.Delivery_Type__c = 'Bite Size';
            serviceCatalogueEntry.Location__c = 'Remote';
            serviceCatalogueEntry.Products__c = 'Access Approve';
            serviceCatalogueEntry.Region__c = 'Asia';
            serviceCatalogueEntry.Service_Type__c = 'Integrations';
            serviceCatalogueEntry.User_Level__c = 'Beginner';

            insert serviceCatalogueEntry;

            Test.startTest();
            List<Service_Catalogues__c> catalogueEntries =  cspServiceCatalogueEntryHandler.getServiceCatalogueEntries(a.Id, '', 4, 0, false, '', '', '', '', '', '', false);
            Test.stopTest();

            System.assertEquals(0, catalogueEntries.size());
        }
    }

    @isTest
    public static void getServiceCatalogueEntryWithProduct() {

        User portalAccountOwner1 = TestUtilities.createUser('Support Admin', 'System Administrator', 'test123');

        System.runAs(portalAccountOwner1) {
            // Create account
    		Account portalAccount1 = new Account(Name = 'TestAccount', OwnerId = portalAccountOwner1.Id);
    		insert portalAccount1;

            //Create contact
			Contact contact1 = new Contact(FirstName = 'Test', 
            Lastname = 'McTesty', 
            AccountId = portalAccount1.Id, 
            Email = System.now().millisecond() + 'test@test.com');

            insert contact1;
            //Create our portal user
            User user1 = TestUtilities.createPortalUser('Customer Portal - Support User', contact1.Id, 'test123p');
        }
        Account a = [SELECT Id FROM Account WHERE Name = 'TestAccount'];
        User u = [SELECT Id, email, ContactId FROM User WHERE alias = 'test123p' LIMIT 1];
        System.runAs(u) {
            Service_Catalogues__c serviceCatalogueEntry = new Service_Catalogues__c();
            serviceCatalogueEntry.Service_Description__c = 'Entry Description';
            serviceCatalogueEntry.Points_Conversion__c = 10000;
            serviceCatalogueEntry.Service_Title__c = 'Catalogue Entry';
            serviceCatalogueEntry.Account_Journey_Stage__c = 'Applicable to all';
            serviceCatalogueEntry.Delivered_By__c = 'Professional Services';
            serviceCatalogueEntry.Delivery_Type__c = 'Bite Size';
            serviceCatalogueEntry.Location__c = 'Remote';
            serviceCatalogueEntry.Products__c = 'Access Applause';
            serviceCatalogueEntry.Region__c = 'Asia';
            serviceCatalogueEntry.Service_Type__c = 'Integrations';
            serviceCatalogueEntry.User_Level__c = 'Beginner';

            Service_Catalogues__c serviceCatalogueEntryWithProduct = new Service_Catalogues__c();
            serviceCatalogueEntryWithProduct.Service_Description__c = 'Entry Description For Product Object';
            serviceCatalogueEntryWithProduct.Points_Conversion__c = 30000;
            serviceCatalogueEntryWithProduct.Service_Title__c = 'Catalogue Entry For Product Object';
            serviceCatalogueEntryWithProduct.Products__c = 'Access Approve';
            serviceCatalogueEntryWithProduct.Account_Journey_Stage__c = 'Applicable to all';
            serviceCatalogueEntryWithProduct.Delivered_By__c = 'Professional Services';
            serviceCatalogueEntryWithProduct.Delivery_Type__c = 'Bite Size';
            serviceCatalogueEntryWithProduct.Location__c = 'Remote';
            serviceCatalogueEntryWithProduct.Region__c = 'Asia';
            serviceCatalogueEntryWithProduct.Service_Type__c = 'Integrations';
            serviceCatalogueEntryWithProduct.User_Level__c = 'Beginner';

            insert serviceCatalogueEntry;
            insert serviceCatalogueEntryWithProduct;

            Test.startTest();
            List<Service_Catalogues__c> catalogueEntries =  cspServiceCatalogueEntryHandler.getServiceCatalogueEntries(a.Id, 'Access Approve', 4, 0, false, 'Integrations', 'Beginner', 'Applicable to all', 'Bite Size', 'Professional Services', 'Remote', false);
            Test.stopTest();

            System.assertEquals(1, catalogueEntries.size());
            Service_Catalogues__c result = catalogueEntries[0];
            System.assertEquals(serviceCatalogueEntryWithProduct.Service_Description__c, result.Service_Description__c);
            System.assertEquals(serviceCatalogueEntryWithProduct.Points_Conversion__c, result.Points_Conversion__c);
            System.assertEquals(serviceCatalogueEntryWithProduct.Service_Title__c, result.Service_Title__c);
        }
    }

    @isTest
    public static void getServiceCatalogue() {

        User portalAccountOwner1 = TestUtilities.createUser('Support Admin', 'System Administrator', 'test123');

        Account portalAccount1 = new Account(Name = 'TestAccount', OwnerId = portalAccountOwner1.Id);

        System.runAs(portalAccountOwner1) {
            //Create account
            insert portalAccount1;

            // Create product routing for allowing access to Access Approve in the portal
            ProductRouting__c routing = new ProductRouting__c();
            routing.Related_Product_Range__c = 'Access Approve';
            routing.Visibility__c = 'Public';
            routing.Product_Division__c = 'No Primary Division';
            insert routing;
            // Create product routing for allowing access to Access Approve in the portal
            ProductRouting__c routing2 = new ProductRouting__c();
            routing2.Related_Product_Range__c = 'Dimensions';
            routing2.Visibility__c = 'Public';
            routing2.Product_Division__c = 'No Primary Division';
            insert routing2;

            // Create entitlement for case creation
            Entitlement ent = new Entitlement(Name = 'TestingEntitlement', 
                                                AccountId = portalAccount1.Id, 
                                                StartDate= Date.valueof(System.now().addDays(-2)), 
                                                EndDate = Date.valueof(System.now().addYears(2)),
                                                AssociatedProductRange__c = 'Access Approve');
            insert ent;

            // Create another entitlement which we won't use
            Entitlement ent2 = new Entitlement(Name = 'TestingEntitlement2', 
                                                AccountId = portalAccount1.Id, 
                                                StartDate= Date.valueof(System.now().addDays(-2)), 
                                                EndDate = Date.valueof(System.now().addYears(2)),
                                                AssociatedProductRange__c = 'Dimensions');
            insert ent2;

            //Create contact
            Contact contact1 = new Contact(FirstName = 'Test', 
                                            Lastname = 'McTesty', 
                                            AccountId = portalAccount1.Id, 
                                            Email = System.now().millisecond() + 'test@test.com');
            insert contact1;

            // Create contact entitlement for a product - note only one here, no contact entitlement for Dimensions
            ContactEntitlement__c cEnt = new ContactEntitlement__c(Real_Entitlement__c = ent.Id,
                                                                    Contact__c = contact1.Id);
            insert cEnt;

            //Create our portal user
            User user1 = TestUtilities.createPortalUser('Customer Portal - Support User', contact1.Id, 'test123p');
        }

        User u = [select Id, email, ContactId from User where alias = 'test123p'];

        System.runAs(u) {
            Service_Catalogues__c serviceCatalogueEntry = new Service_Catalogues__c();
            serviceCatalogueEntry.Service_Description__c = 'Entry Description';
            serviceCatalogueEntry.Points_Conversion__c = 10000;
            serviceCatalogueEntry.Service_Title__c = 'Catalogue Entry';
            serviceCatalogueEntry.Account_Journey_Stage__c = 'Applicable to all';
            serviceCatalogueEntry.Delivered_By__c = 'Professional Services';
            serviceCatalogueEntry.Delivery_Type__c = 'Bite Size';
            serviceCatalogueEntry.Location__c = 'Remote';
            serviceCatalogueEntry.Products__c = 'Access Approve';
            serviceCatalogueEntry.Region__c = 'Asia';
            serviceCatalogueEntry.Service_Type__c = 'Integrations';
            serviceCatalogueEntry.User_Level__c = 'Beginner';

            insert serviceCatalogueEntry;

            Service_Catalogues__c servCat = cspServiceCatalogueEntryHandler.getServiceCatalogue(String.valueOf(serviceCatalogueEntry.Id));
            System.assert( servCat != NULL);
        }
    }

    @isTest
    public static void getRelatedProduct() {

        User portalAccountOwner1 = TestUtilities.createUser('Support Admin', 'System Administrator', 'test123');

        Account portalAccount1 = new Account(Name = 'TestAccount', OwnerId = portalAccountOwner1.Id);

        System.runAs(portalAccountOwner1) {
            //Create account
            insert portalAccount1;

            // Create product routing for allowing access to Access Approve in the portal
            ProductRouting__c routing = new ProductRouting__c();
            routing.Related_Product_Range__c = 'Access Approve';
            routing.Visibility__c = 'Public';
            routing.Product_Division__c = 'No Primary Division';
            insert routing;
            // Create product routing for allowing access to Access Approve in the portal
            ProductRouting__c routing2 = new ProductRouting__c();
            routing2.Related_Product_Range__c = 'Dimensions';
            routing2.Visibility__c = 'Public';
            routing2.Product_Division__c = 'No Primary Division';
            insert routing2;

            // Create entitlement for case creation
            Entitlement ent = new Entitlement(Name = 'TestingEntitlement', 
                                                AccountId = portalAccount1.Id, 
                                                StartDate= Date.valueof(System.now().addDays(-2)), 
                                                EndDate = Date.valueof(System.now().addYears(2)),
                                                AssociatedProductRange__c = 'Access Approve');
            insert ent;

            // Create another entitlement which we won't use
            Entitlement ent2 = new Entitlement(Name = 'TestingEntitlement2', 
                                                AccountId = portalAccount1.Id, 
                                                StartDate= Date.valueof(System.now().addDays(-2)), 
                                                EndDate = Date.valueof(System.now().addYears(2)),
                                                AssociatedProductRange__c = 'Dimensions');
            insert ent2;

            //Create contact
            Contact contact1 = new Contact(FirstName = 'Test', 
                                            Lastname = 'McTesty', 
                                            AccountId = portalAccount1.Id, 
                                            Email = System.now().millisecond() + 'test@test.com');
            insert contact1;

            // Create contact entitlement for a product - note only one here, no contact entitlement for Dimensions
            ContactEntitlement__c cEnt = new ContactEntitlement__c(Real_Entitlement__c = ent.Id,
                                                                    Contact__c = contact1.Id);
            insert cEnt;

            //Create our portal user
            User user1 = TestUtilities.createPortalUser('Customer Portal - Support User', contact1.Id, 'test123p');
        }

        User u = [select Id, email, ContactId from User where alias = 'test123'];

        System.runAs(u) {
            Service_Catalogues__c serviceCatalogueEntry = new Service_Catalogues__c();
            serviceCatalogueEntry.Service_Description__c = 'Entry Description';
            serviceCatalogueEntry.Points_Conversion__c = 10000;
            serviceCatalogueEntry.Service_Title__c = 'Catalogue Entry';
            serviceCatalogueEntry.Account_Journey_Stage__c = 'Applicable to all';
            serviceCatalogueEntry.Delivered_By__c = 'Professional Services';
            serviceCatalogueEntry.Delivery_Type__c = 'Bite Size';
            serviceCatalogueEntry.Location__c = 'Remote';
            serviceCatalogueEntry.Products__c = 'Access Approve';
            serviceCatalogueEntry.Region__c = 'Asia';
            serviceCatalogueEntry.Service_Type__c = 'Integrations';
            serviceCatalogueEntry.User_Level__c = 'Beginner';

            insert serviceCatalogueEntry;

            Map<String, String> product = cspServiceCatalogueEntryHandler.getRelatedProduct(String.valueOf(serviceCatalogueEntry.Id), String.valueOf(portalAccount1.Id));
            List<Map<String,String>> productList = new List<Map<String,String>>();
            productList.add(product);
            System.assert( productList.size() == 1 );
        }
    }

}