force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>Event (e.g. webinar) in Customer Success Portal</description>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>The description of the event, shown in the portal</description>
    <inlineHelpText>The description of the event, shown in the portal</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Featured__c.field-meta.xml
<CustomField>
    <fullName>Featured__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Select if this event should be prioritised in the portal</description>
    <inlineHelpText>Select if this event should be prioritised in the portal</inlineHelpText>
    <label>Featured</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>The product that the event is relevant for, multiples can be selected</description>
    <inlineHelpText>The product that the event is relevant for, multiples can be selected</inlineHelpText>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region(s) that the event is available in</description>
    <inlineHelpText>Region(s) that the event is available in. No value means the event is available in all regions</inlineHelpText>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Community_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the event, shown in portal front-end</description>
    <inlineHelpText>The title of the event, shown in portal front-end</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Featured__c.field-meta.xml
<CustomField>
    <fullName>Featured__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to determine whether a knowledge article should be displayed in the featured articles block in the support community</description>
    <inlineHelpText>Select this checkbox to mark the article as featured</inlineHelpText>
    <label>Featured</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Information_Article_Body__c.field-meta.xml
<CustomField>
    <fullName>Information_Article_Body__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Division__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region(s) that the article is available in</description>
    <inlineHelpText>Region(s) that the article is available in. No value means the article is available in all regions</inlineHelpText>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Community_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/Service_Catalogues__c.object-meta.xml
<CustomObject>
    <label>Services Catalogue</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Service Catalogue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services Catalogue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Catalogues__c/fields/Account_Journey_Stage__c.field-meta.xml
<CustomField>
    <fullName>Account_Journey_Stage__c</fullName>
    <label>Account Journey Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New to Product</fullName>
            </value>
            <value>
                <fullName>In first year of using product</fullName>
            </value>
            <value>
                <fullName>Been using the product for some time</fullName>
            </value>
            <value>
                <fullName>Applicable to all</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Delivered_By__c.field-meta.xml
<CustomField>
    <fullName>Delivered_By__c</fullName>
    <label>Delivered By</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Customer Success Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <label>Delivery Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bite Size</fullName>
            </value>
            <value>
                <fullName>Virtual Classroom</fullName>
            </value>
            <value>
                <fullName>Classroom</fullName>
            </value>
            <value>
                <fullName>1:1 Consulting</fullName>
            </value>
            <value>
                <fullName>1:Many Consulting</fullName>
            </value>
            <value>
                <fullName>Remote Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>Field to identify which division the service catalogue item is associated with</description>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Division</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Remote</fullName>
            </value>
            <value>
                <fullName>Onsite</fullName>
            </value>
            <value>
                <fullName>Access Office Location</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Points_Conversion__c.field-meta.xml
<CustomField>
    <fullName>Points_Conversion__c</fullName>
    <label>Points Conversion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <label>Products</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Community_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Service_Description__c.field-meta.xml
<CustomField>
    <fullName>Service_Description__c</fullName>
    <label>Service Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Service_Title__c.field-meta.xml
<CustomField>
    <fullName>Service_Title__c</fullName>
    <label>Service Title</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Analytics/Reporting</fullName>
            </value>
            <value>
                <fullName>Configurations and Customisation</fullName>
            </value>
            <value>
                <fullName>Education/Training</fullName>
            </value>
            <value>
                <fullName>Flightpath Implementation Extras/Add Ons</fullName>
            </value>
            <value>
                <fullName>Integrations</fullName>
            </value>
            <value>
                <fullName>Strategic Engagements</fullName>
            </value>
            <value>
                <fullName>Upgrade and Migration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Catalogues__c/fields/User_Level__c.field-meta.xml
<CustomField>
    <fullName>User_Level__c</fullName>
    <label>User Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beginner</fullName>
            </value>
            <value>
                <fullName>Competent</fullName>
            </value>
            <value>
                <fullName>Expert</fullName>
            </value>
            <value>
                <fullName>Available for all levels</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/cspGlobalSearchHandlerTest.cls
@isTest(SeeAllData=false)
public with sharing class cspGlobalSearchHandlerTest {

    @isTest
    private static void searchKnowledge() {
        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
            Knowledge__kav newArticle = TestUtilities.getArticleAsADraft('New title', 'new-url-name' + Crypto.getRandomInteger());
            newArticle.Information_Article_Body__c = 'New article';
            newArticle.Division__c = 'Business Management';
            newArticle.Product__c = 'Access Approve';

            insert newArticle;
            String articleId = [SELECT KnowledgeArticleId FROM Knowledge__kav WHERE Id =: newArticle.Id].KnowledgeArticleId;
            KbManagement.PublishingService.publishArticle(articleId, true);

            User portalAccountOwner1 = TestUtilities.createUser('Support Admin', 'System Administrator', 'test123');

            Account portalAccount1 = new Account(Name = 'TestAccount', OwnerId = portalAccountOwner1.Id);
            insert portalAccount1;

            Id [] fixedSearchResults= new Id[1];
            fixedSearchResults[0] = newArticle.Id;
            Test.setFixedSearchResults(fixedSearchResults);

            List<Map<String, Object>> searchResults = cspGlobalSearchHandler.searchKnowledge('New title', 'Access Approve', 5, 0, 'Knowledge__kav', null, true, null, String.valueOf(portalAccount1.Id));

            System.assertEquals(1, searchResults.size());
            System.assert(searchResults.get(0).get('title') == newArticle.Title);
            System.assert(searchResults.get(0).get('url') == '/support/s/article/' + newArticle.UrlName);
        }
    }

    @isTest
    private static void searchReleaseNotes() {
        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
            Knowledge__kav newArticle = new Knowledge__kav();
            newArticle.RecordTypeId = Schema.SObjectType.Knowledge__kav.getRecordTypeInfosByName().get('Release Notes').getRecordTypeId();
            newArticle.Title = 'New title';
            newArticle.UrlName = 'new-url-name' + Crypto.getRandomInteger();
            newArticle.Information_Article_Body__c = 'New article';
            newArticle.Division__c = 'Business Management';
            newArticle.Product__c = 'Access Approve';

            insert newArticle;
            String articleId = [SELECT KnowledgeArticleId FROM Knowledge__kav WHERE Id =: newArticle.Id].KnowledgeArticleId;
            KbManagement.PublishingService.publishArticle(articleId, true);

            User portalAccountOwner1 = TestUtilities.createUser('Support Admin', 'System Administrator', 'test123');

            Account portalAccount1 = new Account(Name = 'TestAccount', OwnerId = portalAccountOwner1.Id);
            insert portalAccount1;

            Id [] fixedSearchResults= new Id[1];
            fixedSearchResults[0] = newArticle.Id;
            Test.setFixedSearchResults(fixedSearchResults);

            List<Map<String, Object>> searchResults = cspGlobalSearchHandler.searchReleaseNotes('New title', 'Access Approve', 5, 0, 'Knowledge__kav', null, true, null, String.valueOf(portalAccount1.Id));

            System.assertEquals(1, searchResults.size());
            System.assert(searchResults.get(0).get('title') == newArticle.Title);
            System.assert(searchResults.get(0).get('url') == '/support/s/article/' + newArticle.UrlName);
        }
    }

    @isTest
    private static void searchCommunities() {

        User portalAccountOwner1 = TestUtilities.createUser('Support Admin', 'System Administrator', 'test123');

		System.runAs(portalAccountOwner1) {
			//Create account
			Account portalAccount1 = new Account(Name = 'TestAccount', OwnerId = portalAccountOwner1.Id);
            insert portalAccount1;
            String accountId = [Select Id from Account where Name = 'TestAccount'].Id;
            FeedItem feed = new FeedItem();
            feed.ParentId = accountId;
            feed.Body = 'Lots of questions';
            feed.Title = 'My title';

            insert feed;

            Id [] fixedSearchResults= new Id[1];
            fixedSearchResults[0] = feed.Id;
            Test.setFixedSearchResults(fixedSearchResults);

            List<Map<String, Object>> listResults = cspGlobalSearchHandler.searchCommunities('questions', '', 1, 0, 'FeedItem', true, null, '', '');
            System.assertEquals(1, listResults.size());

            List<Map<String, Object>> missResults = cspGlobalSearchHandler.searchCommunities('questions', '', 1, 0, 'FeedItem', true, null, 'Not a topic', '');
            System.assertEquals(0, missResults.size());

            missResults = cspGlobalSearchHandler.searchCommunities('questions', '', 1, 0, 'FeedItem', true, null, '', 'Not a group');
            System.assertEquals(0, missResults.size());
        }
    }

    @isTest
    private static void searchServicesCatalogue() {

        User portalAccountOwner1 = TestUtilities.createUser('Support Admin', 'System Administrator', 'test123');

        System.runAs (portalAccountOwner1) {

            Account portalAccount1 = new Account(Name = 'TestAccount', OwnerId = portalAccountOwner1.Id);
            insert portalAccount1;

            //Create contact
            Contact contact1 = new Contact(FirstName = 'Test',
                Lastname = 'McTesty',
                Region__c = 'Europe',
                AccountId = portalAccount1.Id,
                Email = System.now().millisecond() + 'test@test.com');

            insert contact1;
            //Create our portal user
            User user1 = TestUtilities.createPortalUser('Customer Portal - Support User', contact1.Id, 'test123p');

            String accountId = [Select Id from Account where Name = 'TestAccount'].Id;

            Service_Catalogues__c serviceCatalogueEntryWithProduct = new Service_Catalogues__c();
            serviceCatalogueEntryWithProduct.Service_Description__c = 'Entry Description For Product Object';
            serviceCatalogueEntryWithProduct.Points_Conversion__c = 30000;
            serviceCatalogueEntryWithProduct.Service_Title__c = 'Catalogue Entry For Product Object';
            serviceCatalogueEntryWithProduct.Products__c = 'Access Approve';
            serviceCatalogueEntryWithProduct.Account_Journey_Stage__c = 'Applicable to all';
            serviceCatalogueEntryWithProduct.Delivered_By__c = 'Professional Services';
            serviceCatalogueEntryWithProduct.Delivery_Type__c = 'Bite Size';
            serviceCatalogueEntryWithProduct.Location__c = 'Remote';
            serviceCatalogueEntryWithProduct.Region__c = 'Asia';
            serviceCatalogueEntryWithProduct.Service_Type__c = 'Integrations';
            serviceCatalogueEntryWithProduct.User_Level__c = 'Beginner';
            serviceCatalogueEntryWithProduct.Region__c = 'Europe';

            insert serviceCatalogueEntryWithProduct;

            Id [] fixedSearchResults= new Id[1];
            fixedSearchResults[0] = serviceCatalogueEntryWithProduct.Id;
            Test.setFixedSearchResults(fixedSearchResults);

            List<Map<String, Object>> searchResults = cspGlobalSearchHandler.searchServicesCatalogue('Catalogue Entry For Product Object', 'Access Approve', 10, 0, 'Service_Catalogues__c', null, true, null, String.valueOf(portalAccount1.Id));

            System.assertEquals(1, searchResults.size());
            System.assertEquals(serviceCatalogueEntryWithProduct.Service_Title__c, searchResults.get(0).get('title'));
            String serviceCatalogueURL = String.format('/support/s/services?serviceId={0}', new List<String>{serviceCatalogueEntryWithProduct.Id});
            System.assertEquals(serviceCatalogueURL, searchResults.get(0).get('url'));
        }
    }

    @isTest
    private static void listKnowledge() {
        Knowledge__kav newArticle = TestUtilities.getArticleAsADraft('New title', 'new-url-name' + Crypto.getRandomInteger());

        insert newArticle;
        String articleId = [SELECT KnowledgeArticleId FROM Knowledge__kav WHERE Id =: newArticle.Id].KnowledgeArticleId;
        KbManagement.PublishingService.publishArticle(articleId, true);

        List<Map<String, Object>> listResults = cspGlobalSearchHandler.listKnowledge('', '', false, 1, 0, 'Knowledge__kav');

        System.assertEquals(1, listResults.size());
        System.assert(listResults.get(0).get('title') == newArticle.Title);
        System.assert(listResults.get(0).get('url') == '/support/s/article/' + newArticle.UrlName);
    }

    @isTest
    private static void listKnowledgeByProductFeature() {
        Knowledge__kav newArticle = TestUtilities.getArticleAsADraft('New title', 'new-url-name' + Crypto.getRandomInteger());
        newArticle.Division__c = 'Business Management';
        newArticle.Product__c = 'Access Approve';
        newArticle.Product_Features__c = 'Configuration';
        newArticle.Featured__c = true;

        insert newArticle;
        String articleId = [SELECT KnowledgeArticleId FROM Knowledge__kav WHERE Id =: newArticle.Id].KnowledgeArticleId;
        KbManagement.PublishingService.publishArticle(articleId, true);

        List<Map<String, Object>> listResults = cspGlobalSearchHandler.listKnowledge('Access Approve', 'Configuration', true, 1, 0, 'Knowledge__kav');

        System.assertEquals(1, listResults.size());
        System.assert(listResults.get(0).get('product') == newArticle.Product__c);
        System.assert(listResults.get(0).get('productCategory') == newArticle.Product_Features__c);
    }

    @isTest
    private static void listCommunities() {

        User portalAccountOwner1 = TestUtilities.createUser('Support Admin', 'System Administrator', 'test123');

		System.runAs(portalAccountOwner1) {
			//Create account
			Account portalAccount1 = new Account(Name = 'TestAccount', OwnerId = portalAccountOwner1.Id);
            insert portalAccount1;
            String accountId = [Select Id from Account where Name = 'TestAccount'].Id;
            FeedItem feed = new FeedItem();
            feed.ParentId = accountId;
            feed.Body = 'Lots of questions';

            insert feed;

            List<Map<String, Object>> listResults = cspGlobalSearchHandler.listCommunities('', '', 1, 0, 'FeedItem');

            System.assertEquals(1, listResults.size());
        }
    }




    @isTest
    private static void searchEvents() {
        
         User portalAccountOwner1 = TestUtilities.createUser('Support Admin', 'System Administrator', 'test123');

		System.runAs(portalAccountOwner1) {
			//Create account
			Account portalAccount1 = new Account(Name = 'TestAccount', OwnerId = portalAccountOwner1.Id);
            insert portalAccount1;
            String accountId = [Select Id from Account where Name = 'TestAccount'].Id;
            Event__c event = new Event__c();
            event.Title__c = 'A webinar title';
            event.Product__c = 'Access Approve';
            event.Description__c = 'Description of the webinar';
            insert event;

            Id [] fixedSearchResults= new Id[1];
            fixedSearchResults[0] = event.Id;
            Test.setFixedSearchResults(fixedSearchResults);

            List<Map<String, Object>> listResults = cspGlobalSearchHandler.searchEvents('webinar', 'Access Approve', 1, 0, 'Event__c', true, null, String.valueOf(portalAccount1.Id));

            System.assertEquals(1, listResults.size());
        }
    }
}