force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>Event (e.g. webinar) in Customer Success Portal</description>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>The product that the event is relevant for, multiples can be selected</description>
    <inlineHelpText>The product that the event is relevant for, multiples can be selected</inlineHelpText>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Recording_Link__c.field-meta.xml
<CustomField>
    <fullName>Recording_Link__c</fullName>
    <description>The link to the recoding of the event, used in the portal</description>
    <inlineHelpText>The link to the recoding of the event, used in the portal</inlineHelpText>
    <label>Recording Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region(s) that the event is available in</description>
    <inlineHelpText>Region(s) that the event is available in. No value means the event is available in all regions</inlineHelpText>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Community_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Division__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region(s) that the article is available in</description>
    <inlineHelpText>Region(s) that the article is available in. No value means the article is available in all regions</inlineHelpText>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Community_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Note__c/Release_Note__c.object-meta.xml
<CustomObject>
    <label>Release Note</label>
    <nameField>
        <label>Release Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Release Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release_Note__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Release Notes</relationshipLabel>
    <relationshipName>Release_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release_Note__c/fields/Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Knowledge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Knowledge</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Release Notes</relationshipLabel>
    <relationshipName>Release_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release_Note__c/fields/Postponed__c.field-meta.xml
<CustomField>
    <fullName>Postponed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Postponed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Release_Note__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Note__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region(s) that the release note is available in</description>
    <inlineHelpText>Region(s) that the release note is available in. No value means the release note is available in all regions</inlineHelpText>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Community_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Note__c/fields/Release_Details__c.field-meta.xml
<CustomField>
    <fullName>Release_Details__c</fullName>
    <label>Release Details</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full program</fullName>
            </value>
            <value>
                <fullName>Service pack</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Workspace app</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Note__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Automated</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Note__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/cspReleaseNoteHandler.cls
public with sharing class cspReleaseNoteHandler {
    @AuraEnabled(cacheable=true)
    public static List<Map<String, Object>> getReleaseNotes(String product, Integer amount, Integer offset) {
        List<Map<String, Object>> releaseNotes = new List<Map<String, Object>>();
        String networkName = cspReleaseNoteHandler.getNetwork();
        String contactRegion = getContactRegion();
        String query = 'SELECT Id, Product__c, Version__c, Knowledge__c, Knowledge__r.Title, Knowledge__r.UrlName, Release_Date__c, Type__c, Postponed__c, Event__r.Recording_Link__c, Release_Details__c FROM Release_Note__c Where id != null ';

        query += String.isNotBlank(product) ? ' AND Product__c =:product' : '';

        query += String.isNotEmpty(contactRegion) ? ' AND (Region__c = \'\' OR Region__c includes (\'' + contactRegion + '\'))' : '';

        query += String.format(' ORDER BY Release_Date__c DESC LIMIT {0} OFFSET {1}', new List<Object>{++amount, offset});

        for (Release_Note__c n: Database.query(query)) {
            releaseNotes.add(new Map<String, Object>{
                'id' => n.Id,
                'version' => n.Version__c,
                'product' => n.Product__c,
                'releaseDate' => n.Release_Date__c,
                'releaseNotes' => n.Knowledge__r.Title,
                'recordingLink' => n.Event__r.Recording_Link__c,
                'upgradeType' => n.Type__c,
                'postponed' => n.Postponed__c,
                'articleUrl' => '/' + networkName + '/s/article/' + n.Knowledge__r.UrlName,
                'component' => n.Release_Details__c
            });
        }
        return releaseNotes;
    }

    private static String getNetwork() {
        try {
            return [ SELECT UrlPathPrefix FROM Network WHERE Id = :Network.getNetworkId() ].UrlPathPrefix;
        } catch(QueryException e) {
            System.debug('Exception retrieving network id : ' + e.getMessage());
            return 'support';
        }
    }

    @TestVisible private static String getContactRegion() {
        String userId = Userinfo.getUserid();
        User currentUser = Database.query('SELECT ContactId, Contact.Region__c FROM User WHERE Id =: userId');
        if (currentUser != null && String.isNotBlank(currentUser.ContactId) && String.isNotEmpty(currentUser.Contact.Region__c)) {
            String region = currentUser.Contact.Region__c;
            return currentUser.Contact.Region__c;
        }
        return '';
    }
}