force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>Event (e.g. webinar) in Customer Success Portal</description>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>The description of the event, shown in the portal</description>
    <inlineHelpText>The description of the event, shown in the portal</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>The scheduled duration (in minutes) of the event</description>
    <inlineHelpText>The scheduled duration (in minutes) of the event</inlineHelpText>
    <label>Duration (minutes)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>The product that the event is relevant for, multiples can be selected</description>
    <inlineHelpText>The product that the event is relevant for, multiples can be selected</inlineHelpText>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>The date and time when the event is due to start</description>
    <inlineHelpText>The date and time when the event is due to start</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Success_Plan__c.field-meta.xml
<CustomField>
    <fullName>Success_Plan__c</fullName>
    <description>The success plans the event is relevant for, multiples can be selected</description>
    <inlineHelpText>The success plans the event is relevant for, multiples can be selected</inlineHelpText>
    <label>Success Plan</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PlanType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the event, shown in portal front-end</description>
    <inlineHelpText>The title of the event, shown in portal front-end</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/cspEventsTest.cls
@isTest
public with sharing class cspEventsTest {
    @testSetup
    static void testSetup() {
        insert new Event__c(
            Title__c = 'test',
            Description__c = 'Testing',
            Product__c = 'Access Approve',
            Start__c = Date.today().addDays(2)
        );

        insert new Event__c(
            Title__c = 'test',
            Description__c = 'Testing',
            Product__c = 'Access Capture',
            Success_Plan__c = 'Premier',
            Start__c = Date.today().addDays(1)
        );

        insert new Event__c(
            Title__c = 'test',
            Description__c = 'Testing',
            Product__c = 'Access Approve',
            Duration__c = 60,
            Success_Plan__c = 'Premier',
            Start__c = Date.today().addDays(-2)
        );
    }

    @isTest
    public static void itShouldReturnEventsForProduct() {
        System.Test.startTest();

        List<Map<String, Object>> results = cspEvents.getEvents(new Map<String, Object> {
            'name' => 'Access Approve',
            'id' => '123456789'
        }, 'All', 0, 10);

        System.Test.stopTest();

        System.assertEquals(2, results.size(), 'There should be two results in Access Approve with category all');
    }

    @isTest
    public static void itShouldReturnFutureEventsForProduct() {
        System.Test.startTest();

        List<Map<String, Object>> results = cspEvents.getEvents(new Map<String, Object> {
            'name' => 'Access Capture',
            'id' => '123456789'
        }, 'All', 0, 10);

        System.Test.stopTest();

        System.assertEquals(true, (Boolean)results.get(0).get('future'), 'The event should be marked as future');
    }

    @isTest
    public static void itShouldReturnEventsForCategory() {
        System.Test.startTest();

        List<Map<String, Object>> results = cspEvents.getEvents(new Map<String, Object> {
            'name' => 'Access Approve',
            'id' => '123456789'
        }, 'previous_webinars', 0, 10);

        System.Test.stopTest();

        System.assertEquals(2, results.size(), 'There should be a result in previous webinars');
    }

    @isTest
    public static void itShouldReturnNotEventsForCategory() {
        System.Test.startTest();

        List<Map<String, Object>> results = cspEvents.getEvents(new Map<String, Object> {
            'name' => 'Access CRM',
            'id' => '123456789'
        }, 'All', 0, 10);

        System.Test.stopTest();

        System.assertEquals(null, results, 'There should be no results for Access CRM');
    }

    @isTest
    public static void itShouldReturnPremierEvents() {
        System.Test.startTest();

        List<Map<String, Object>> results = cspEvents.getEvents(new Map<String, Object> {
            'name' => 'Access Capture',
            'id' => '123456789'
        }, 'upcoming_webinars', 0, 10);


        System.Test.stopTest();

        System.assertEquals(true, (Boolean)results.get(0).get('premier'), 'The second event should be marked as a premier event');
    }

    @isTest
    public static void itShouldReturnAnEvent() {
        System.Test.startTest();
        System.debug([SELECT Id, Name FROM Event__c]);

        Map<String, Object> results = cspEvents.getEvent([SELECT Name FROM Event__c LIMIT 1].Name);

        System.Test.stopTest();

        System.assertEquals('test', (String)results.get('title'), 'The event should have a title of test');
    }

    @IsTest Public Static Void TestGetContactRegion() {
        String region = cspEvents.getContactRegion();
        System.assert(region == '');
    }
}