force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>Event (e.g. webinar) in Customer Success Portal</description>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>The description of the event, shown in the portal</description>
    <inlineHelpText>The description of the event, shown in the portal</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>The scheduled duration (in minutes) of the event</description>
    <inlineHelpText>The scheduled duration (in minutes) of the event</inlineHelpText>
    <label>Duration (minutes)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>The product that the event is relevant for, multiples can be selected</description>
    <inlineHelpText>The product that the event is relevant for, multiples can be selected</inlineHelpText>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductRange</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Recording_Link__c.field-meta.xml
<CustomField>
    <fullName>Recording_Link__c</fullName>
    <description>The link to the recoding of the event, used in the portal</description>
    <inlineHelpText>The link to the recoding of the event, used in the portal</inlineHelpText>
    <label>Recording Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region(s) that the event is available in</description>
    <inlineHelpText>Region(s) that the event is available in. No value means the event is available in all regions</inlineHelpText>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Community_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Registration_Link__c.field-meta.xml
<CustomField>
    <fullName>Registration_Link__c</fullName>
    <description>The link to the registration for the event, used in the portal</description>
    <inlineHelpText>The link to the registration for the event, used in the portal</inlineHelpText>
    <label>Registration Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>The date and time when the event is due to start</description>
    <inlineHelpText>The date and time when the event is due to start</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Success_Plan__c.field-meta.xml
<CustomField>
    <fullName>Success_Plan__c</fullName>
    <description>The success plans the event is relevant for, multiples can be selected</description>
    <inlineHelpText>The success plans the event is relevant for, multiples can be selected</inlineHelpText>
    <label>Success Plan</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PlanType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the event, shown in portal front-end</description>
    <inlineHelpText>The title of the event, shown in portal front-end</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/recordTypes/Access_World.recordType-meta.xml
<RecordType>
    <fullName>Access_World</fullName>
    <active>true</active>
    <label>Access World</label>
</RecordType>

force-app/main/default/classes/cspEvents.cls
public with sharing class cspEvents {
    @AuraEnabled(cacheable=true)
    public static List<Map<String, Object>> getEvents(Map<String, Object> product, String category, Integer offset, Integer amount) {
        String categoryFilter = 'Start__c != null';
        String productName = null;
        String plan = null;
        Boolean internalPlan = false;
        String ContactRegion = getContactRegion();

        if(product != null && product.get('id') != null) {
            plan = checkPlan((String)product.get('successPlanName'));
            productName = (String)product.get('name');
            // Internal users see all events
            internalPlan = plan == 'Internal';
        }

        if(category == 'upcoming_webinars') {
            categoryFilter = 'RecordType.Name = \'Online Event\' AND Start__c >= TODAY';
        } else if(category == 'previous_events') {
            categoryFilter = 'Start__c < TODAY AND (RecordType.Name = \'Online Event\' OR RecordType.Name = \'Access World\')';
        } else if(category == 'user_group_events') {
            categoryFilter = 'RecordType.Name = \'Onsite Events\'';
        } else if(category == 'access_world') {
            categoryFilter = 'RecordType.Name = \'Access World\'';
        }

        String query = 'SELECT ' +
            'Name, Title__c, Description__c, Start__c, Recording_Link__c, ' +
            'Duration__c, Registration_Link__c, Success_Plan__c ' +
            'FROM Event__c ' +
            'WHERE ' + categoryFilter + ' ' +
            (product == null ? '' : 'AND Product__c includes (:productName) ') +
            (String.isNotEmpty(contactRegion) ? 'AND (Region__c = \'\' OR Region__c includes (\'' + contactRegion + '\')) ' : '') +
            (category == 'upcoming_webinars' ? 'ORDER BY Start__c ASC ' : 'ORDER BY Start__c DESC ') +
            'LIMIT ' + ++amount + ' ' +
            'OFFSET :offset';

        List<Map<String, Object>> events = new List<Map<String, Object>>();
        for(Event__c event: Database.query(query)) {
            Boolean premierPlan = false;
            Boolean inactive = true;
            if(event.Success_Plan__c != null) {
                // It's a premier event if only the premier plan is selected
                premierPlan = event.Success_Plan__c == 'Premier';
                // Event is noly visible if the customer's plan is available
                inactive = plan == null || !event.Success_Plan__c.contains(plan);
            }
            events.add(new Map<String, Object> {
                'id' => event.Id,
                'name' => event.Name,
                'start' => event.Start__c,
                'title' => event.Title__c,
                'description' => event.Description__c,
                'duration' => event.Duration__c,
                'registrationLink' => event.Registration_Link__c,
                'recordingLink' => event.Recording_Link__c,
                'premier' => premierPlan,
                'future' => event.Start__c > Datetime.now(),
                'inactive' => internalPlan ? false : inactive
            });
        }

        return events.size() > 0 ? events : null;
    }

    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getEvent(String eventId) {
        Event__c event = [
            SELECT
                Name, Title__c, Description__c, Start__c, Recording_Link__c,
                Duration__c, Registration_Link__c, Success_Plan__c
            FROM Event__c
            WHERE Name =: eventId
        ];

        Boolean premierPlan = false;
        if(event.Success_Plan__c != null && event.Success_Plan__c.contains('Premier')) {
            premierPlan = true;
        }

        return new Map<String, Object> {
            'id' => event.Id,
            'name' => event.Name,
            'start' => event.Start__c,
            'title' => event.Title__c,
            'description' => event.Description__c,
            'duration' => event.Duration__c,
            'registrationLink' => event.Registration_Link__c,
            'recordingLink' => event.Recording_Link__c,
            'premier' => premierPlan,
            'future' => event.Start__c > Datetime.now()
        };
    }

    private static String checkPlan(String planName) {
        if (String.isEmpty(planName)) {
            return null;
        }
        if (planName.containsIgnoreCase('Premier')) {
            return 'Premier';
        }
        if (planName.containsIgnoreCase('Standard')) {
            return 'Standard';
        }
        if (planName.containsIgnoreCase('Essential')) {
            return 'Essential';
        }
        return planName;
    }

    @TestVisible private static String getContactRegion() {
        String userId = Userinfo.getUserid();
        User currentUser = Database.query('SELECT ContactId, Contact.Region__c FROM User WHERE Id =: userId');
        if (currentUser != null && String.isNotBlank(currentUser.ContactId) && String.isNotEmpty(currentUser.Contact.Region__c)) {
            String region = currentUser.Contact.Region__c;
            return currentUser.Contact.Region__c;
        }
        return '';
    }
}